<?php echo $this->getChildHtml('items_before'); ?>

<div id="checkout-review-table-wrapper" class="mobile-table">
    <table class="table data-table" id="checkout-review-table" cellspacing="0">
        <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
        <col width="1"/>
        <col width="1"/>
        <col width="1"/>
        <col width="1"/>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <col width="1"/>
            <col width="1"/>
        <?php endif; ?>
        <col width="1"/>
        <thead>
        <tr>
            <th rowspan="<?php echo $rowspan ?>" ><?php echo Mage::helper("Ave40_Translate")->__('Selected Item(s)') ?></th>
            <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo Mage::helper("Ave40_Translate")->__('Unit Price') ?></th>
            <th rowspan="<?php echo $rowspan ?>" wrap="wrap" class="a-center"><?php echo Mage::helper("Ave40_Translate")->__('Qty') ?></th>
            <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo Mage::helper("Ave40_Translate")->__('Subtotal') ?></th>
        </tr>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <tr>
                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                <!--<th></th> -->
            </tr>
        <?php endif; ?>
        </thead>
        <?php echo $this->getChildHtml('totals'); ?>
        <tbody>

        <?php foreach ($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item) ?>
        <?php endforeach ?>
        </tbody>

    </table>
</div>
<?php echo $this->getChildHtml('items_after'); ?>
<script type="text/javascript">//jQuery('#checkout-review-table').decorate('table');</script>
<div id="checkout-review-submit">
    <?php if (Mage::getStoreConfig('lotusbreath_onestepcheckout/revieworder/show_link_cart')):?>
    <p class=""><?php echo Mage::helper("Ave40_Translate")->__('Forgot an Item?') ?> <a
            href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo Mage::helper("Ave40_Translate")->__('Edit Your Cart') ?></a></p>
    <?php endif;?>
    <?php
        $canEditCart = Mage::getStoreConfig('lotusbreath_onestepcheckout/revieworder/can_edit_cart');
    ?>
    <?php if ($canEditCart):?>
    <div class="lt-buttons-set right" id="review-buttons-container">
        <button type="button" name="edit_cart_action" id="edit_cart_action"
                value="update_qty" title="<?php echo Mage::helper("Ave40_Translate")->__('Edit Your Cart') ?>" class="button btn-update">
            <span><span><?php echo Mage::helper("Ave40_Translate")->__('Edit Your Cart') ?></span></span></button>
        <button type="button" name="edit_cart_action" id="update_cart_action"
                value="update_qty" title="<?php echo Mage::helper("Ave40_Translate")->__('Update') ?>" class="button btn-update" style="display: none;">
            <span><span><?php echo Mage::helper("Ave40_Translate")->__('Update') ?></span></span></button>
        <button type="button" name="edit_cart_action" id="cancel_cart_action"
                value="update_qty" title="<?php echo Mage::helper("Ave40_Translate")->__('Cancel') ?>" class="button btn-close" style="display: none;"m>
            <span><span><?php echo Mage::helper("Ave40_Translate")->__('Cancel') ?></span></span></button>
    </div>

    <?php endif;?>
    
</div>
<div id="checkout-paypaliframe-load" class="authentication white-popup mfp-hide"></div>
<div class="clearfix"></div>
<script type="text/javascript">
    //<![CDATA[
    review = new Review();
    //]]>
</script>


