<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = Mage::helper("Ave40_Translate")->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <label for="qty"><?php echo Mage::helper("Ave40_Translate")->__('Qty:') ?></label>
		<a rel="nofollow" class="reduce" href="javascript:void(0);" id="qty-dec"></a>
        <input type="text" name="qty" id="qty" maxlength="12" value="<?php if($this->getProductDefaultQty()==0){echo 1;}else{ echo $this->getProductDefaultQty()*1;} ?>" title="<?php echo Mage::helper("Ave40_Translate")->__('Qty') ?>" class="input-text qty" />
        <a rel="nofollow" class="add" href="javascript:void(0);" id="qty-inc"></a>
        <?php endif; ?>
        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart btn-round" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
  <script type="text/javascript">
    //<![CDATA[
      jQuery("#qty-inc").click( function () {
	    var qty=Number(jQuery("#qty").val());
        if(qty<999)
		{
		  jQuery("#qty").val(qty+1);
		}
		else
		{
		 jQuery("#qty").val(999);
		}
	  });
	       jQuery("#qty-dec").click( function () {
	    var qty=Number(jQuery("#qty").val());
        if(qty>1)
		{
		  jQuery("#qty").val(qty-1);
		}
		else
		{
		 jQuery("#qty").val(1);
		}
	  });

	//]]>
    </script>
