<?php
/**
 * lotusbreath
 */
?>

<?php
    $relatedLocationFields = Mage::getStoreConfig("lotusbreath_onestepcheckout/general/location_fields");
    if ($relatedLocationFields){
        $relatedLocationFields = explode(',',$relatedLocationFields);
    }else{
        $relatedLocationFields = array('postcode', 'country_id', 'region_id','city');
    }
    $isAllowGuest = Mage::helper('checkout')->isAllowedGuestCheckout(Mage::getSingleton('checkout/session')->getQuote());
    $isCheckEmailExists = false;
    if (!$isAllowGuest && !Mage::getSingleton('customer/session')->isLoggedIn())
        $isCheckEmailExists = true;


$defaultShippingID = $this->getCustomer()->getDefaultShipping();
$defaultAddress = null;
$allAddress = $this->getCustomer()->getAddresses();

if(!empty($allAddress)) {
    if($defaultShippingID) {
        unset($allAddress[$defaultShippingID]);
        $defaultAddress = Mage::getModel('customer/address')->load($defaultShippingID);
    } else {
        $defaultAddress = array_shift($allAddress);
    }
}

?>



<!--
        ave40-default-address:默认地址class

-->

<div style="color:red;" id="billing-error" class="error"></div>
<fieldset class="ship-address-info-content cart-toggle-module">

    <ul class="form-list ">
        <?php if ($this->customerHasAddresses()): ?>
    <div class="ave40-ship-list ave40-ship-address-box">
                <ul class="ave40-ship-address-list bg-f6 clearfix">
			
			<?php if($defaultAddress): ?>
            <!-- 默认地址 -->
            <li class="ave40-ship-address-items ave40-default-address active ave40-ship-item" data-value="<?php echo $defaultAddress->getId() ?>">
                <div class="ave40-ship-item-info">
                    <div class="ave40-ship-item-top">
                        <span class="ave40-ship-item-name"><?php echo $defaultAddress->getName() ?></span>
                        <span class="ave40-ship-item-action">
                            <i class="ship-default-select-icon iconfont icon-qizi_icon" title="Default address"></i>
                            <i class="ship-default-triangle-icon"></i>

                        </span>
                    </div>
                    <div class="ave40-ship-item-bottom">
						<span>
                            T: <?php echo $defaultAddress->getTelephone() ?><br>
							<?php echo $defaultAddress->getCity() ?>,<?php echo $defaultAddress->getRegion() ?><br>
                            <?php echo implode("\n", $defaultAddress->getStreet()) ?><br>
                            <?php echo $defaultAddress->getPostcode() ?><br>
						</span>
                    </div>
                </div>
            </li>
			<?php endif; ?>
					
					
            <!-- 其他地址 默认隐藏-->
			<?php if(!empty($allAddress)): ?>
			<?php /** @var Mage_Customer_Model_Address $_addr */ ?>
			<?php foreach ($allAddress as $_addr):?>
            <li class="ave40-ship-address-items ave40-ship-item ave40-hide" data-value="<?php echo $_addr->getId() ?>">
                <div class="ave40-ship-item-info">
                    <div class="ave40-ship-item-top">
                        <span class="ave40-ship-item-name"><?php echo $_addr->getName() ?></span>
                        <span class="ave40-ship-item-action">

                            <i class="ship-default-select-icon iconfont icon-qizi_icon" title="Default address"></i>
                            <i class="ship-default-triangle-icon"></i>

                        </span>
                    </div>
                    <div class="ave40-ship-item-bottom">
                        <span>
							T: <?php echo $_addr->getTelephone() ?><br>
                            <?php echo $_addr->getCity() ?>,<?php echo $_addr->getRegion() ?><br>
                            <?php echo implode("\n", $_addr->getStreet()) ?><br>
                            <?php echo $_addr->getPostcode() ?><br>
						</span>
                    </div>
                </div>
            </li>
			<?php endforeach;?>
			<?php endif; ?>
					
            <!--more-->
            <li class="ave40-ship-address-more ave40-ship-operate ave40-ship-item">
                <div class="ave40-ship-address-more-btn">
                    <i class="iconfont icon-more"></i>
                    <span>More</span>
                </div>
            </li>
            <!-- 新增地址 -->
            <li class="ave40-ship-add-new-address ave40-ship-address-items ave40-ship-operate ave40-ship-item" data-value="">
                <div class="ave40-ship-add-new-address-btn">
                    <i class="iconfont icon-add"></i>
                    <span>New Address</span>
                </div>
            </li>
        </ul>

    </div>

            <li style="display: none">
                <p style="width: 250px;display: none" ><?php echo Mage::helper("Ave40_Translate")->__('Select a billing address from your address book or enter a new address.') ?></p>

                <div class="input-box select-address">
                    <?php echo $this->getAddressesHtmlSelect('billing') ?>
                </div>
                <h2 class="ship-address-show"></h2>
            </li>
        <?php endif; ?>
        <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
            <fieldset>
                <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>"
                       id="billing:address_id"/>
                <ul>
                    <div class="main-info-fields">
                        <?php if (!$this->isCustomerLoggedIn()): ?>
                            <li class="fields">
                                    <label for="billing:email"
                                           class="required"><span class="asterisk">*</span><?php echo Mage::helper("Ave40_Translate")->__('Email') ?></label>

                                    <div class="input-box input-box-wide">
                                        <input type="text" name="billing[email]" id="billing:email"
                                               value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>"
                                               title="<?php echo Mage::helper("Ave40_Translate")->__('Email Address') ?>"
                                               data-validate="{required:true, 'validate-email':true }"
                                               placeholder="<?php echo Mage::helper("Ave40_Translate")->__('Email Address'); ?>"
                                               class="input-text validate-email billing_email required-entry <?php echo $isCheckEmailExists ? 'check-email-exists' : '';?>"/>
                                    </div>


                            </li>
                        <?php endif; ?>
                        <li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?></li>
                        <li class="fields billing-company-box" style="margin: 0">

                            <?php if (Mage::getStoreConfig('lotusbreath_onestepcheckout/billingaddress/allowshowcompanyfield')): ?>

                                    <label for="billing:company"><?php echo Mage::helper("Ave40_Translate")->__('Company') ?></label>

                                    <div class="input-box input-box-wide">
                                        <input type="text" id="billing:company" name="billing[company]"
                                               value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>"
                                               title="<?php echo Mage::helper("Ave40_Translate")->__('Company') ?>"
                                               class="input-text <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('company') ?>"/>
                                    </div>

                            <?php endif; ?>
                        </li>

                        <li class="fields">
                            <div class="field checkout-tel">
                                <label for="billing:telephone"
                                       class="required"><span class="asterisk">*</span><?php echo Mage::helper("Ave40_Translate")->__('Phone No.') ?></label>

                                <div class="input-box input-box-wide">
                                    <input type="text" name="billing[telephone]"
                                           value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>"
                                           title="<?php echo Mage::helper("Ave40_Translate")->__('Telephone') ?>"
                                           placeholder="<?php echo Mage::helper("Ave40_Translate")->__('Phone Number') ?>"
                                           class="input-text billing_telephone <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('telephone') ?>"
                                           id="billing:telephone"/>
                                </div>
                            </div>
                            <?php if (Mage::getStoreConfig('lotusbreath_onestepcheckout/billingaddress/allowshowfaxfield')): ?>
                                <div class="field">
                                    <label for="billing:fax"><?php echo Mage::helper("Ave40_Translate")->__('Fax') ?></label>

                                    <div class="input-box">
                                        <input type="text" name="billing[fax]"
                                               value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>"
                                               title="<?php echo Mage::helper("Ave40_Translate")->__('Fax') ?>"
                                               class="input-text  <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('fax') ?>"
                                               id="billing:fax"/>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </li>
                    </div>
                    <div class="address-fields">
                        <?php $_streetValidationClass = $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('street'); ?>
                        <li class="fields">
                            <label for="billing:street1" class="required"><span class="asterisk">*</span><?php echo Mage::helper("Ave40_Translate")->__('Address') ?>

                            </label>

                            <div class="input-box input-box-wide">
                                <input type="text" title="<?php echo Mage::helper("Ave40_Translate")->__('Street Address') ?>"
                                       name="billing[street][]" id="billing:street1"
                                       PLACEHOLDER="<?php echo Mage::helper("Ave40_Translate")->__('Street Address') ?>"
                                       value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>"
                                       class="input-text billing_street1 <?php echo $_streetValidationClass ?>"/>
                            </div>
                        </li>
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                            <li class="fields">
                                <div class="input-box input-box-wide">
                                    <input type="text" title="<?php echo Mage::helper("Ave40_Translate")->__('Street Address %s', $_i) ?>"
                                           name="billing[street][]" id="billing:street<?php echo $_i ?>"
                                           PLACEHOLDER="<?php echo Mage::helper("Ave40_Translate")->__('Apartment,Suit,Unit(etc)') ?>"
                                           value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>"
                                           class="input-text billing_street2 <?php echo $_streetValidationClass ?>"/>
                                </div>
                            </li>
                        <?php endfor; ?>
                        <?php
                        $isShowVATNumber = Mage::getStoreConfig('lotusbreath_onestepcheckout/billingaddress/allowshowvatnumberfield');
                        if ($isShowVATNumber && $this->helper('lotusbreath_onestepcheckout')->isVatAttributeVisible()) :
                        //if ($isShowVATNumber):
                        ?>

                            <li class="fields">
                                <div class="field">
                                <label for="billing:vat_id" class="required">
                                    <span class="asterisk">*</span>
                                    <?php echo Mage::helper("Ave40_Translate")->__('VAT Number') ?></label>
                                <div class="input-box">
                                    <input type="text" id="billing:vat_id" name="billing[vat_id]"
                                           value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>"
                                           title="<?php echo Mage::helper("Ave40_Translate")->__('VAT Number') ?>"
                                           class="input-text <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('vat_id') ?>"/>
                                </div>
                                </div>
                            </li>
                        <?php endif; ?>
                        <li class="fields">
                            <div class="field city-box">
                                <?php
                                $changeLocationClass = '';
                                if (in_array('city', $relatedLocationFields))
                                    $changeLocationClass = 'change_location_field';
                                ?>
                                <label for="billing:city" class="required" style="display: none"><span class="asterisk">*</span><?php echo Mage::helper("Ave40_Translate")->__('City') ?></label>

                                <div class="input-box">
                                    <input type="text" title="<?php echo Mage::helper("Ave40_Translate")->__('City') ?>" name="billing[city]"
                                           value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
                                           placeholder="<?php echo Mage::helper("Ave40_Translate")->__('City'); ?>"
                                           class="<?php echo $changeLocationClass;?> billing_city input-text <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('city') ?>"
                                           id="billing:city"/>
                                </div>
                            </div>
                            <div class="field region ">

                                <label for="billing:region_id"
                                       class="required hide" style="display: none"><span class="asterisk">*</span><?php echo Mage::helper("Ave40_Translate")->__('State/Province') ?></label>

                                <div class="input-box">
                                    <?php
                                    $changeLocationClass = '';

                                    if (in_array('region_id', $relatedLocationFields))
                                        $changeLocationClass = 'change_location_field';
                                    ?>
                                    <select id="billing:region_id" name="billing[region_id]"
                                            title="<?php echo Mage::helper("Ave40_Translate")->__('State/Province') ?>" class="validate-select "
                                            class=" <?php echo $changeLocationClass;?> "
                                            style="display:none;"
                                            <?php if (Mage::getStoreConfig('general/region/display_all') == false):?>disabled="disabled"<?php endif; ?>
                                        >
                                        <option
                                            value=""><?php echo Mage::helper("Ave40_Translate")->__('Please select region, state or province') ?></option>
                                    </select>
                                    <script type="text/javascript">
                                        //<![CDATA[
                                        $('billing:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
                                        //]]>
                                    </script>
                                    <input type="text" id="billing:region" name="billing[region]"
                                           value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
                                           title="<?php echo Mage::helper("Ave40_Translate")->__('State/Province') ?>"
                                           placeholder="<?php echo Mage::helper("Ave40_Translate")->__('State/Province'); ?>"
                                           required="required"
                                           class=" <?php echo $changeLocationClass;?> input-text <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('region') ?>"
                                           style="display:none;"
                                           <?php if (Mage::getStoreConfig('general/region/display_all') == false):?>disabled="disabled"<?php endif; ?>
                                        />
                                </div>
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field">
                                <label for="billing:postcode"
                                       class="required " style="display: none"><span class="asterisk">*</span><?php echo Mage::helper("Ave40_Translate")->__('Zip/Postal Code') ?></label>

                                <div class="input-box">
                                    <?php
                                    $changeLocationClass = '';
                                    if (in_array('postcode', $relatedLocationFields))
                                        $changeLocationClass = 'change_location_field';
                                    ?>
                                    <input type="text" title="<?php echo Mage::helper("Ave40_Translate")->__('Zip/Postal Code') ?>"
                                           name="billing[postcode]" id="billing:postcode"
                                           placeholder="<?php echo Mage::helper("Ave40_Translate")->__('Zip/Postal Code'); ?>"
                                           value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
                                           class="<?php echo $changeLocationClass; ?> billing_postcode input-text validate-zip-international <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('postcode') ?>"/>
                                </div>
                            </div>
                            <div class="field billing-country">
                                <label for="billing:country_id"
                                       class="required" style="display: none"><span class="asterisk">*</span><?php echo Mage::helper("Ave40_Translate")->__('Country') ?></label>
                                <div class="input-box">
                                    <?php echo $this->getCountryHtmlSelect('billing') ?>
                                    <script>

                                        /**
                                         *  添加常用国家
                                         */
                                        ~function ($) {
                                            var billing_country = $("#billing\\:country_id");
                                            var selectedValue = billing_country.find("option:selected").val();
                                            var optgroupValue = ['US','CA','GB','DK','FR','RU','DE','MY'];

                                            var optgroupHtml = $(
                                                '<option value="US">United States</option>' +
                                                '<option value="CA">Canada</option>' +
                                                '<option value="GB">United Kingdom</option>' +
                                                '<option value="DK">Denmark</option>' +
                                                '<option value="FR">France</option>' +
                                                '<option value="RU">Russia</option>' +
                                                '<option value="ES">Spain</option>' +
                                                '<option value="DE">Germany</option>' +
                                                '<option value="MY">Malaysia</option>' +
                                                '<option class="optgroup_hr" value="" disabled="disabled">------------</option>');

                                            billing_country.find('option').first().after(optgroupHtml);
                                            billing_country.addClass('chosen-country-select').attr('data-placeholder','Choose a Country...');

                                            $.each(optgroupValue,function(index,value){
                                                if (selectedValue == value){
                                                    billing_country.find(" option[value = '"+value+"']").eq(0).attr("selected","selected");
                                                }
                                            });

                                            $('#billing\\:country_id').change(function () {
                                                $('#billing\\:region').val('');
                                            })

                                        }(jQuery)

                                    </script>
                                </div>
                                <?php
                                $changeLocationClass = '';
                                if (in_array('country_id', $relatedLocationFields)):
                                    $changeLocationClass = 'change_location_field';

                                ?>
                                <script>
                                    var billingCountry = document.getElementById("billing:country_id");
                                    billingCountry.setAttribute('class', billingCountry.getAttribute('class') + ' <?php echo $changeLocationClass;?>');

                                </script>
                                <?php endif;?>
                                <?php
                                $changeLocationClass = '';
                                if (in_array('region_id', $relatedLocationFields)):
                                    $changeLocationClass = 'update-location-region-class';
                                ?>
                                <script>
                                    var billingCountry = document.getElementById("billing:country_id");
                                    billingCountry.setAttribute('class', billingCountry.getAttribute('class') + ' <?php echo $changeLocationClass;?>');

                                </script>
                                <?php endif;?>
                            </div>
                        </li>

                        <?php if (!$this->isCustomerLoggedIn()): ?>

                            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                            <?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
                                <li class="fields">
                                    <?php if ($_dob->isEnabled()): ?>
                                        <div class="field">
                                            <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                        </div>
                                    <?php endif; ?>
                                    <?php if ($_gender->isEnabled()): ?>
                                        <div class="field">
                                            <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                        </div>
                                    <?php endif ?>
                                </li>
                            <?php endif ?>

                            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                            <?php if ($_taxvat->isEnabled()): ?>
                                <li>
                                    <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                </li>
                            <?php endif ?>
                            <?php /*if ($isAllowGuest):*/?><!--
                            <li class="fields create-new-account-box">
                                <input type="checkbox" name="billing[create_new_account]"
                                       value=1/> <?php /*echo Mage::helper("Ave40_Translate")->__("Register new account"); */?>?
                            </li>
                            <?php /*else: */?>
                                <p><strong><?php /*echo Mage::helper("Ave40_Translate")->__("Register new account - Enter your password:"); */?></strong></p>
                            --><?php /*endif; */?>
                            <?php $passwordLiId = $isAllowGuest ? 'register-customer-password' : ''; ?>
                            <!--
                            <li class="fields customer-password-box" id="<?php /*echo $passwordLiId;*/?>">
                                <div class="field">
                                    <label for="billing:customer_password"
                                           class="required" style="display: none"><span class="asterisk">*</span><?php /*echo Mage::helper("Ave40_Translate")->__('Password') */?></label>

                                    <div class="input-box">
                                        <input type="password" name="billing[customer_password]"
                                               placeholder="password"
                                               id="billing:customer_password" title="<?php /*echo Mage::helper("Ave40_Translate")->__('Password') */?>"
                                               class="input-text required-entry validate-password"/>
                                    </div>
                                </div>
                                <div class="field">
                                    <label for="billing:confirm_password"
                                           class="required" style="display: none"><span class="asterisk">*</span><?php /*echo Mage::helper("Ave40_Translate")->__('Confirm Password') */?></label>

                                    <div class="input-box">
                                        <input type="password" name="billing[confirm_password]"
                                               title="<?php /*echo Mage::helper("Ave40_Translate")->__('Confirm Password') */?>"
                                               id="billing:confirm_password"
                                               placeholder="Confirm Password"
                                               class="input-text required-entry validate-cpassword"/>
                                    </div>
                                </div>
                            </li>
                            -->
                        <?php endif; ?>
                        <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()): ?>
                            <li class="control">
                                <input type="checkbox" name="billing[save_in_address_book]" value="1"
                                       title="<?php echo Mage::helper("Ave40_Translate")->__('Save in address book') ?>"
                                       id="billing:save_in_address_book"
                                       onchange="if(window.shipping) shipping.setSameAsBilling(false);"
                                       checked="checked"
                                       class="checkbox"/><label
                                    for="billing:save_in_address_book"><?php echo Mage::helper("Ave40_Translate")->__('Save in address book') ?></label>
                            </li>
                        <?php else: ?>
                            <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1"/>
                            </li>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                    </div>

                </ul>
            </fieldset>
        </li>
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('checkout.onepage.billing.extra') ?>
        <?php
            $alwaysusesameasbilling = Mage::getStoreConfig('lotusbreath_onestepcheckout/shippingaddress/alwaysusesameasbilling');
        ?>
        <?php if ($this->canShip() && $alwaysusesameasbilling == false): ?>
            <li class="control">
                <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes"
                       value="1"<?php if ($this->isUseBillingAddressForShipping()) { ?> checked="checked"<?php } ?>
                       title="<?php echo Mage::helper("Ave40_Translate")->__('Ship to this address') ?>"
                        class="radio"/><label
                    for="billing:use_for_shipping_yes"><?php echo Mage::helper("Ave40_Translate")->__('Ship to this address') ?></label></li>
            <li class="control">
                <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no"
                       value="0"<?php if (!$this->isUseBillingAddressForShipping()) { ?> checked="checked"<?php } ?>
                       title="<?php echo Mage::helper("Ave40_Translate")->__('Ship to different address') ?>"
                        class="radio"/><label
                    for="billing:use_for_shipping_no"><?php echo Mage::helper("Ave40_Translate")->__('Ship to different address') ?></label>
            </li>
        <?php endif; ?>
    </ul>
    <?php if (!$this->canShip() || $alwaysusesameasbilling == true): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1"/>
    <?php endif; ?>

</fieldset>


<script type="text/javascript">
    ~function ($) {
        $(function () {

            /**
             * 点击选中收货地址
             *
             */
            $('.ave40-ship-address-items').on('click',function () {
                $(this).addClass('active').siblings('.ave40-ship-address-items').removeClass('active')
            });

            $('.ave40-ship-address-more').on('click',function () {
                $(this).hide().siblings('.ave40-ship-address-items').removeClass('ave40-hide');

            });


            $('.ave40-ship-add-new-address').on('click',function () {
                $('#billing-address-select').val('').trigger('change');
            });

            $('.ave40-ship-address-list').find('.ave40-ship-address-items').on('click',function () {
                var address_val = $(this).data('value');
                $('#billing-address-select').val(address_val).trigger('change');
            })
        })
    }(jQuery)


</script>

<script type="text/javascript">
    //<![CDATA[
    var billing = new Billing();

</script>
