<?php if (!Mage::helper('customer')->isLoggedIn()) : ?>
    <form class="white-popup mfp-hide" id="loginFrm" action="<?php echo $this->getUrl('onestepcheckout/index/login') ?>" method="POST"
          >
        <h3><?php echo Mage::helper("Ave40_Translate")->__("Login"); ?></h3>
        <p class="mage-error" id="loginFrmErrMsg"></p>
        <fieldset>
            <ul class="form-list" style="">
                <li>
                    <div class="input-box">
                        <label for="login-email"><?php echo Mage::helper("Ave40_Translate")->__("Email"); ?><em>*</em></label>
                        <input type="text" class="input-text required-entry validate-email" id="login-email"
                               name="login[username]" value="">
                    </div>
                </li>
                <li>
                    <div class="input-box">
                        <label for="login-password"><?php echo Mage::helper("Ave40_Translate")->__("Password"); ?><em>*</em></label>
                        <input type="password" class="input-text required-entry" id="login-password"
                               name="login[password]">
                    </div>
                </li>
            </ul>
            <div class="buttons-set">
                <a href="<?php echo Mage::getUrl("customer/account/forgotpassword/"); ?>" class="f-left">
                    <?php echo Mage::helper("Ave40_Translate")->__("Forgot your password?"); ?></a>
                <button type="submit" class="button"><span><span>Login</span></span></button>
            </div>
        </fieldset>
    </form>
<?php endif; ?>
