<script type="text/javascript">
	Translator.add('Please enter a valid email address.','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Please enter a valid email address.')?>');
	Translator.add('This field is required.','<?php echo Mage::helper('Ave40_Translate')->translateForJs('This field is required.')?>');
	Translator.add('Please fix this field.','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Please fix this field.')?>');
	Translator.add('Please enter a valid URL.','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Please enter a valid URL.')?>');
	Translator.add('Please enter a valid date.','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Please enter a valid date.')?>');
	Translator.add('Please enter a valid number.','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Please enter a valid number.')?>');
	Translator.add('Please enter a valid date (ISO).','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Please enter a valid date (ISO).')?>');
	Translator.add('Please enter only digits.','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Please enter only digits.')?>');
	Translator.add('Please enter a valid credit card number.','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Please enter a valid credit card number.')?>');
	Translator.add('Please enter the same value again.','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Please enter the same value again.')?>');
	Translator.add('Searching..','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Searching..')?>');
	Translator.add('Adding to the cart','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Adding to the cart')?>');
	Translator.add('Successful Operation!','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Successful Operation!')?>');
	Translator.add('Please wait...','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Please wait...')?>');
	Translator.add('You have successfully logged in','<?php echo Mage::helper('Ave40_Translate')->translateForJs('You have successfully logged in')?>');
	Translator.add('You have successfully logged in and registered, This page is jumpping to the Personal Information Page...','<?php echo Mage::helper('Ave40_Translate')->translateForJs('You have successfully logged in and registered, This page is jumpping to the Personal Information Page...')?>');
	Translator.add('Please enter no more than {0} characters.','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Please enter no more than {0} characters.')?>');
	Translator.add('Please enter at least {0} characters.','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Please enter at least {0} characters.')?>');
	Translator.add('Please enter a value between {0} and {1} characters long.','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Please enter a value between {0} and {1} characters long.')?>');
	Translator.add('Please enter a value between {0} and {1}.','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Please enter a value between {0} and {1}.')?>');
	Translator.add('Please enter a value less than or equal to {0}.','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Please enter a value less than or equal to {0}.')?>');
	Translator.add('please enter a value greater than or equal to {0}.','<?php echo Mage::helper('Ave40_Translate')->translateForJs('please enter a value greater than or equal to {0}.')?>');
	Translator.add('verification code sent successfully','<?php echo Mage::helper('Ave40_Translate')->translateForJs('verification code sent successfully')?>');
	Translator.add('Your password has been updated','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Your password has been updated')?>');
	Translator.add('verification code sent successfully','<?php echo Mage::helper('Ave40_Translate')->translateForJs('verification code sent successfully')?>');
	Translator.add('Arse you sure you want to delete this address?','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Arse you sure you want to delete this address?')?>');
	Translator.add('You can check our wholesale prices on product page now!','<?php echo Mage::helper('Ave40_Translate')->translateForJs('You can check our wholesale prices on product page now!')?>');
	Translator.add('Sending inquire','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Sending inquire')?>');
	Translator.add('Thank you for your subscription.','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Thank you for your subscription.')?>');
	Translator.add('Online Inquiry','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Online Inquiry')?>');
	Translator.add('Our experts will contact you in 1 minute','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Our experts will contact you in 1 minute')?>');
	Translator.add('Please specify the product\'s option(s).','<?php echo Mage::helper('Ave40_Translate')->translateForJs('Please specify the product\'s option(s).')?>')
</script>

