
<?php
/**
 * Template for displaying product price in different places (products grid, product view page etc)
 *
 * @see Mage_Catalog_Block_Product_Abstract
 */
?>
<?php
	$_coreHelper = $this->helper('core');
	$_weeeHelper = $this->helper('weee');
	$_taxHelper  = $this->helper('tax');
	/* @var $_coreHelper Mage_Core_Helper_Data */
	/* @var $_weeeHelper Mage_Weee_Helper_Data */
	/* @var $_taxHelper Mage_Tax_Helper_Data */
	
	$_product = $this->getProduct();
	/** @var Ave40_Base_Helper_Customer $customerHelper */
	$customerHelper = Mage::helper('ave40_base/customer');
	
	/**
	 * 批发用户组显示最低批发价格
	 */
	if($customerHelper->getIsGuidePageCustomer() || $customerHelper->isWholesaleUser()) {
        $tierPrice = $_product->getTierPrice();
       
        if(!empty($tierPrice)) {
            $minprice = null;
           
            foreach($tierPrice as $priceData) {
                if($minprice === null) {
                    $minprice = floatval($priceData['price']);
                } else {
                    $minprice = $minprice > floatval($priceData['price']) ? floatval($priceData['price']) : $minprice;
                }
            }
           
            if($_product->getFinalPrice() === null || floatval($_product->getFinalPrice()) > $minprice) {
                $_product->setPrice($minprice);
                $_product->setFinalPrice($minprice);
            }
        }
	}
	
	$_id = $_product->getId();
	$_weeeSeparator = '';
	$_simplePricesTax = ($_taxHelper->displayPriceIncludingTax() || $_taxHelper->displayBothPrices());
	$_minimalPriceValue = $_product->getMinimalPrice();
	$_minimalPrice = $_taxHelper->getPrice($_product, $_minimalPriceValue, $_simplePricesTax);
?>

<?php if (!$_product->isGrouped()): ?>
	<?php $_weeeTaxAmount = $_weeeHelper->getAmountForDisplay($_product); ?>
	<?php if ($_weeeHelper->typeOfDisplay($_product, array(1,2,4))): ?>
		<?php $_weeeTaxAmount = $_weeeHelper->getAmount($_product); ?>
		<?php $_weeeTaxAttributes = $_weeeHelper->getProductWeeeAttributesForDisplay($_product); ?>
	<?php endif; ?>

	<div class="price-box">
	<?php $_price = $_taxHelper->getPrice($_product, $_product->getPrice()) ?>
	<?php $_regularPrice = $_taxHelper->getPrice($_product, $_product->getPrice(), $_simplePricesTax) ?>
	<?php $_finalPrice = $_taxHelper->getPrice($_product, $_product->getFinalPrice()) ?>
	<?php $_finalPriceInclTax = $_taxHelper->getPrice($_product, $_product->getFinalPrice(), true) ?>
	<?php $_weeeDisplayType = $_weeeHelper->getPriceDisplayType(); ?>
	<?php if ($_finalPrice == $_price): ?>
		<?php if ($_taxHelper->displayBothPrices()): ?>
			<?php if ($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 0)): // including ?>
				<span class="price-excluding-tax">
					<span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
					<span class="price" id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
						<?php echo $_coreHelper->currency($_price+$_weeeTaxAmount,true,false) ?>
					</span>
				</span>
				<span class="price-including-tax">
					<span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
					<span class="price" id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
						<?php echo $_coreHelper->currency($_finalPriceInclTax+$_weeeTaxAmount,true,false) ?>
					</span>
				</span>
			<?php elseif ($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 1)): // incl. + weee ?>
				<span class="price-excluding-tax">
					<span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
					<span class="price" id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
						<?php echo $_coreHelper->currency($_price+$_weeeTaxAmount,true,false) ?>
					</span>
				</span>
				<span class="price-including-tax">
					<span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
					<span class="price" id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
						<?php echo $_coreHelper->currency($_finalPriceInclTax+$_weeeTaxAmount,true,false) ?>
					</span>
					<span class="weee">(
						<?php foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
							<?php echo $_weeeSeparator; ?>
							<?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount(), true, true); ?>
							<?php $_weeeSeparator = ' + '; ?>
						<?php endforeach; ?>
						)</span>
				</span>
			<?php elseif ($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 4)): // incl. + weee ?>
				<span class="price-excluding-tax">
					<span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
					<span class="price" id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
						<?php echo $_coreHelper->currency($_price+$_weeeTaxAmount,true,false) ?>
					</span>
				</span>
				<span class="price-including-tax">
					<span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
					<span class="price" id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
						<?php echo $_coreHelper->currency($_finalPriceInclTax+$_weeeTaxAmount,true,false) ?>
					</span>
					<span class="weee">(
						<?php foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
							<?php echo $_weeeSeparator; ?>
							<?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(), true, true); ?>
							<?php $_weeeSeparator = ' + '; ?>
						<?php endforeach; ?>
						)</span>
				</span>
			<?php elseif ($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 2)): // excl. + weee + final ?>
				<span class="price-excluding-tax">
					<span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
					<span class="price" id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
						<?php echo $_coreHelper->currency($_price,true,false) ?>
					</span>
				</span>
				<?php foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
					<span class="weee">
						<?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount(), true, true); ?>
					</span>
				<?php endforeach; ?>
				<span class="price-including-tax">
					<span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
					<span class="price" id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
						<?php echo $_coreHelper->currency($_finalPriceInclTax+$_weeeTaxAmount,true,false) ?>
					</span>
				</span>
			<?php else: ?>
				<span class="price-excluding-tax">
					<span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
					<span class="price" id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
						<?php echo $_coreHelper->currency($_price,true,false) ?>
					</span>
				</span>
				<span class="price-including-tax">
					<span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
					<span class="price" id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
						<?php echo $_coreHelper->currency($_finalPriceInclTax,true,false) ?>
					</span>
				</span>
			<?php endif; ?>
		<?php else: ?>
			<?php if ($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 0)): // including ?>
				<span class="regular-price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
					<?php echo $_coreHelper->currency($_price+$_weeeTaxAmount,true,true) ?>
				</span>
			<?php elseif ($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 1)): // incl. + weee ?>
				<span class="regular-price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
					<?php echo $_coreHelper->currency($_price+$_weeeTaxAmount,true,true) ?>
				</span>
				<span class="weee">(
					<?php foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
						<?php echo $_weeeSeparator; ?>
						<?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount(), true, true); ?>
						<?php $_weeeSeparator = ' + '; ?>
					<?php endforeach; ?>
					)</span>
			<?php elseif ($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 4)): // incl. + weee ?>
				<span class="regular-price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
					<?php echo $_coreHelper->currency($_price+$_weeeTaxAmount,true,true) ?>
				</span>
				<span class="weee">(
					<?php foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
						<?php echo $_weeeSeparator; ?>
						<?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(), true, true); ?>
						<?php $_weeeSeparator = ' + '; ?>
					<?php endforeach; ?>
					)</span>
			<?php elseif ($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 2)): // excl. + weee + final ?>
				<span class="regular-price"><?php echo $_coreHelper->currency($_price,true,true) ?></span><br />
				<?php foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
					<span class="weee">
						<?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount(), true, true); ?>
					</span>
				<?php endforeach; ?>
				<span class="regular-price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
					<?php echo $_coreHelper->currency($_price+$_weeeTaxAmount,true,true) ?>
				</span>
			<?php else: ?>
				<span class="regular-price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
					<?php echo $_coreHelper->currency($_price,true,true) ?>
				</span>
			<?php endif; ?>
		<?php endif; ?>
	<?php else: /* if ($_finalPrice == $_price): */ ?>
		<?php $_originalWeeeTaxAmount = $_weeeHelper->getOriginalAmount($_product); ?>

		<?php if ($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 0)): // including ?>
            <?php /* 引导页面, 批发用户不显示原价 */ ?>
            <?php if(!$customerHelper->getIsGuidePageCustomer() && !$customerHelper->isLoginAsWholesales()): ?>
			<p class="old-price">
				<span class="price-label"><?php echo Mage::helper("Ave40_Translate")->__('Regular Price:') ?></span>
				<span class="price" id="old-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
					<?php echo $_coreHelper->currency($_regularPrice+$_originalWeeeTaxAmount,true,false) ?>
				</span>
			</p>
			<?php endif; ?>

			<?php if ($_taxHelper->displayBothPrices()): ?>
				<p class="special-price">
					<span class="price-label"><?php echo Mage::helper("Ave40_Translate")->__('Special Price:') ?></span>
					<span class="price-excluding-tax">
						<span class="label"><?php echo $_taxHelper->__('Excl. Tax:') ?></span>
						<span class="price" id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
							<?php echo $_coreHelper->currency($_finalPrice+$_weeeTaxAmount,true,false) ?>
						</span>

					</span>
					<?php $special_percent = ceil(100 - (( 100/$_regularPrice ) * $_finalPrice ));?>
					<span class="percent-off"><?php echo $special_percent.'% Off'; ?></span>
				<span class="price-including-tax">
					<span class="label"><?php echo $_taxHelper->__('Incl. Tax:') ?></span>
					<span class="price" id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
						<?php echo $_coreHelper->currency($_finalPriceInclTax+$_weeeTaxAmount,true,false) ?>
					</span>
				</span>
				</p>
			<?php else: ?>
			<p class="special-price">
				<span class="price-label"><?php echo Mage::helper("Ave40_Translate")->__('Special Price:') ?></span>
				<span class="price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
					<?php echo $_coreHelper->currency($_finalPrice+$_weeeTaxAmount,true,false) ?>
				</span>
				<?php $special_percent = ceil(100 - (( 100/$_regularPrice ) * $_finalPrice ));?>
				<span class="percent-off"><?php echo $special_percent.'% Off'; ?></span>
			</p>
			<?php endif; ?>

		<?php elseif ($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 1)): // incl. + weee ?>
            <?php /* 引导页面, 批发用户不显示原价 */ ?>
            <?php if(!$customerHelper->getIsGuidePageCustomer() && !$customerHelper->isLoginAsWholesales()): ?>
			<p class="old-price">
				<span class="price-label"><?php echo Mage::helper("Ave40_Translate")->__('Regular Price:') ?></span>
				<span class="price" id="old-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
					<?php echo $_coreHelper->currency($_regularPrice+$_originalWeeeTaxAmount,true,false) ?>
				</span>
			</p>
			<?php endif; ?>

			<p class="special-price">
				<span class="price-label"><?php echo Mage::helper("Ave40_Translate")->__('Special Price:') ?></span>
				<span class="price-excluding-tax">
					<span class="label"><?php echo $_taxHelper->__('Excl. Tax:') ?></span>
					<span class="price" id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
						<?php echo $_coreHelper->currency($_finalPrice+$_weeeTaxAmount,true,false) ?>
					</span>
					<?php $special_percent = ceil(100 - (( 100/$_regularPrice ) * $_finalPrice ));?>
					<span class="percent-off"><?php echo $special_percent.'% Off'; ?></span>
				</span>
			<span class="weee">(
				<?php foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
					<?php echo $_weeeSeparator; ?>
					<?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount(), true, true); ?>
					<?php $_weeeSeparator = ' + '; ?>
				<?php endforeach; ?>
				)</span>
			<span class="price-including-tax">
				<span class="label"><?php echo $_taxHelper->__('Incl. Tax:') ?></span>
				<span class="price" id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
					<?php echo $_coreHelper->currency($_finalPriceInclTax+$_weeeTaxAmount,true,false) ?>
				</span>
			</span>
			</p>
		<?php elseif ($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 4)): // incl. + weee ?>
            <?php /* 引导页面, 批发用户不显示原价 */ ?>
            <?php if(!$customerHelper->getIsGuidePageCustomer() && !$customerHelper->isLoginAsWholesales()): ?>
			<p class="old-price">
				<span class="price-label"><?php echo Mage::helper("Ave40_Translate")->__('Regular Price:') ?></span>
				<span class="price" id="old-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
					<?php echo $_coreHelper->currency($_regularPrice+$_originalWeeeTaxAmount,true,false) ?>
				</span>
			</p>
			<?php endif; ?>
			<p class="special-price">
				<span class="price-label"><?php echo Mage::helper("Ave40_Translate")->__('Special Price:') ?></span>
				<span class="price-excluding-tax">
					<span class="label"><?php echo $_taxHelper->__('Excl. Tax:') ?></span>
					<span class="price" id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
						<?php echo $_coreHelper->currency($_finalPrice+$_weeeTaxAmount,true,false) ?>
					</span>
					<?php $special_percent = ceil(100 - (( 100/$_regularPrice ) * $_finalPrice ));?>
					<span class="percent-off"><?php echo $special_percent.'% Off'; ?></span>
				</span>
			<span class="weee">(
				<?php foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
					<?php echo $_weeeSeparator; ?>
					<?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(), true, true); ?>
					<?php $_weeeSeparator = ' + '; ?>
				<?php endforeach; ?>
				)</span>
			<span class="price-including-tax">
				<span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
				<span class="price" id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
					<?php echo $_coreHelper->currency($_finalPriceInclTax+$_weeeTaxAmount,true,false) ?>
				</span>
			</span>
			</p>
		<?php elseif ($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, 2)): // excl. + weee + final ?>
            <?php /* 引导页面, 批发用户不显示原价 */ ?>
            <?php if(!$customerHelper->getIsGuidePageCustomer() && !$customerHelper->isLoginAsWholesales()): ?>
			<p class="old-price">
				<span class="price-label"><?php echo Mage::helper("Ave40_Translate")->__('Regular Price:') ?></span>
				<span class="price" id="old-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
					<?php echo $_coreHelper->currency($_regularPrice,true,false) ?>
				</span>
			</p>
			<?php endif; ?>
			<p class="special-price">
				<span class="price-label"><?php echo Mage::helper("Ave40_Translate")->__('Special Price:') ?></span>
				<span class="price-excluding-tax">
					<span class="label"><?php echo $_taxHelper->__('Excl. Tax:') ?></span>
					<span class="price" id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
						<?php echo $_coreHelper->currency($_finalPrice,true,false) ?>
					</span>
					<?php $special_percent = ceil(100 - (( 100/$_regularPrice ) * $_finalPrice ));?>
					<span class="percent-off"><?php echo $special_percent.'% Off'; ?></span>
				</span>
				<?php foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
					<span class="weee">
						<?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $_coreHelper->currency($_weeeTaxAttribute->getAmount(), true, true); ?>
					</span>
				<?php endforeach; ?>
				<span class="price-including-tax">
					<span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
					<span class="price" id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
						<?php echo $_coreHelper->currency($_finalPriceInclTax+$_weeeTaxAmount,true,false) ?>
					</span>
				</span>
			</p>
		<?php else: // excl. ?>

			<?php if ($_taxHelper->displayBothPrices()): ?>
				<p class="special-price">
					<span class="price-label"><?php echo Mage::helper("Ave40_Translate")->__('Special Price:') ?></span>
					<span class="price-excluding-tax">
						<span class="label"><?php echo $_taxHelper->__('Excl. Tax:') ?></span>
						<span class="price" id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
							<?php echo $_coreHelper->currency($_finalPrice,true,false) ?>
						</span>
					</span>
					<span class="price-including-tax">
						<span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
						<span class="price" id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
							<?php echo $_coreHelper->currency($_finalPriceInclTax,true,false) ?>
						</span>
					</span>
					<?php $special_percent = ceil(100 - (( 100/$_regularPrice ) * $_finalPrice ));?>
					<span class="percent-off"><?php echo $special_percent.'% Off'; ?></span>
				</p>
			<?php else: ?>
			<p class="special-price">
				<span class="price-label"><?php echo Mage::helper("Ave40_Translate")->__('Special Price:') ?></span>
				<span class="price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
					<?php echo $_coreHelper->currency($_finalPrice,true,false) ?>
				</span>
				<?php $special_percent = ceil(100 - (( 100/$_regularPrice ) * $_finalPrice ));?>
				<span class="percent-off"><?php echo $special_percent.'% Off'; ?></span>
			</p>
			<?php endif; ?>
            
            <?php /* 引导页面, 批发用户不显示原价 */ ?>
            <?php if(!$customerHelper->getIsGuidePageCustomer() && !$customerHelper->isLoginAsWholesales()): ?>
			<p class="old-price">
				<span class="price-label"><?php echo Mage::helper("Ave40_Translate")->__('Regular Price:') ?></span>
				<span class="price" id="old-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
					<?php echo $_coreHelper->currency($_regularPrice,true,false) ?>
				</span>
			</p>
			<?php endif; ?>
		<?php endif; ?>

	<?php endif; /* if ($_finalPrice == $_price): */ ?>

	<?php if ($this->getDisplayMinimalPrice() && $_minimalPriceValue && $_minimalPriceValue < $_product->getFinalPrice()): ?>

		<?php $_minimalPriceDisplayValue = $_minimalPrice; ?>
		<?php if ($_weeeTaxAmount && $_weeeHelper->typeOfDisplay($_product, array(0, 1, 4))): ?>
			<?php $_minimalPriceDisplayValue = $_minimalPrice+$_weeeTaxAmount; ?>
		<?php endif; ?>

		<?php if ($this->getUseLinkForAsLowAs()):?>
		<a href="<?php echo $_product->getProductUrl(); ?>" class="minimal-price-link">
		<?php else:?>
		<span class="minimal-price-link">
		<?php endif?>
			<span class="label"><?php echo Mage::helper("Ave40_Translate")->__('As low as:') ?></span>
			<span class="price" id="product-minimal-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
				<?php echo $_coreHelper->currency($_minimalPriceDisplayValue,true,false) ?>
			</span>
		<?php if ($this->getUseLinkForAsLowAs()):?>
		</a>
		<?php else:?>
		</span>
		<?php endif?>
	<?php endif; /* if ($this->getDisplayMinimalPrice() && $_minimalPrice && $_minimalPrice < $_finalPrice): */ ?>
	</div>

<?php else: /* if (!$_product->isGrouped()): */ ?>
	<?php
	$_exclTax = $_taxHelper->getPrice($_product, $_minimalPriceValue, $includingTax = null);
	$_inclTax = $_taxHelper->getPrice($_product, $_minimalPriceValue, $includingTax = true);
	?>
	<?php if ($this->getDisplayMinimalPrice() && $_minimalPriceValue): ?>
		<div class="price-box">
			<p class="minimal-price">
				<span class="price-label"><?php echo Mage::helper("Ave40_Translate")->__('Starting at:') ?></span>
				<?php if ($_taxHelper->displayBothPrices()): ?>
					<span class="price-excluding-tax">
						<span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
						<span class="price" id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
							<?php echo $_coreHelper->currency($_exclTax, true, false) ?>
						</span>
					</span>
					<span class="price-including-tax">
						<span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
						<span class="price" id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
							<?php echo $_coreHelper->currency($_inclTax, true, false) ?>
						</span>
					</span>
				<?php else: ?>
					<?php
					$_showPrice = $_inclTax;
					if (!$_taxHelper->displayPriceIncludingTax()) {
						$_showPrice = $_exclTax;
					}
					?>
				<span class="price" id="product-minimal-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
					<?php echo $_coreHelper->currency($_showPrice, true, false) ?>
				</span>
				<?php endif; ?>
			</p>
		</div>
	<?php endif; /* if ($this->getDisplayMinimalPrice() && $_minimalPrice): */ ?>
<?php endif; /* if (!$_product->isGrouped()): */ ?>
