<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2011 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 * @var $this Ave40_Catalog_Block_Product_View
 */
?>
<script type="text/javascript">
    var allProductInfo = <?php echo json_encode($this->getAllProductInfo()) ?>;
    //var quoteProductInfo = <?php //echo json_encode($this->getProductQtyInfoFromQuote()) ?>//;
    var quoteProductInfo = {};
</script>
<script type="text/javascript" src="<?php _insert_asset_url('js/product/page.js') ?>"></script>
<link rel="stylesheet" href="<?php _insert_asset_url('css/product/page.css') ?>">
<input type="hidden" id="currency_symbol" value="<?php echo $this->getCurrencySymbol() ?>">

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="details_contair quickViewPopup ">
    <div class="goods-info" product_id="<?= $this->getProduct()->getId() ?>" product_type="<?php echo $this->getProduct()->getTypeId() ?>">
        <div class="product-info clearfix">
            <?php echo $this->getProductMediaHtml() ?>

            <form action="" method="post"
                  id="product_addtocart_form" <?= $this->getProduct()->getOptions() ? 'enctype="multipart/form-data"' : '' ?>>
                <div class="product-detail">
                    <?php /* 特价 */ ?>
                    <?php if ($this->getProduct()->getSpecialPrice() && $this->getProduct()->getSpecialToDate()): ?>
                        <div class="promo-end">
                            <div class="promo-end-box">
                                Promo ends in
                                <i class="time">
                                    <span class="day">0</span>&nbsp;day(s)&nbsp;
                                    <span class="hour">00</span>:
                                    <span class="minute">00</span>:
                                    <span class="second">00</span>
                                </i>
                            </div>
                        </div>
                    <?php endif ?>

                    <?php /* 预售标签 */ ?>
                    <?php if ($this->getProduct()->getData('pre_sales')): ?>
                        <?php $pre_arrival_date = strtotime($this->getProduct()->getData('pre_arrival_date')); ?>
                        <?php if ($pre_arrival_date && $pre_arrival_date > time()): ?>
                            <div class="pre-sales promo-end">
                                <div class="promo-end-box">
                                    <span>Expected Date of Arrival</span>
                                    <i class="pre-sales-end-time">
                                        <span class="month"><?= date('n', $pre_arrival_date) ?></span>/<span class="day"><?= date('j', $pre_arrival_date) ?></span>/<span class="year"><?= date('Y', $pre_arrival_date) ?></span>
                                    </i>
                                </div>
                            </div>
                        <?php endif ?>
                    <?php endif ?>

                    <h1 class="product-title clearfix">
                        <?php $preOrderInfo = $this->getProductPreOrder() ?>
                        <?php if ($preOrderInfo['is_pre_order']): ?>
                            <?php if($preOrderInfo['partial']): ?>
                                <span class="left">PARTIAL PRE-ORDER</span>&nbsp;
                            <?php else: ?>
                                <span class="left">PRE-ORDER</span>&nbsp;
                            <?php endif ?>
                        <?php endif ?>
                        <div><?php echo $this->getCatalogOutputHelper()->productAttribute($this->getProduct(), $this->getProduct()->getName(), 'name') ?></div>
                    </h1>

                    <?php if ($this->getAve40CatalogHelper()->getProductTagCode($this->getProduct()) == 'onlyshow'): ?>
                        <div class="coming-soon-product-tips">
                            <img src="<?php echo $this->getSkinUrl('images/product/comsoon.png') ?>" alt="">
                            <h2>Coming Soon</h2>
                            <p>This product will be available in the near future.Please stay tuned.</p>
                        </div>
                    <?php else: ?>
                        <?php
                        Mage::unregister('ave40_instance_product_items_block');
                        Mage::register('ave40_instance_product_items_block', new Varien_Object([
                            'attr_enable_rating_bar' => 1
                        ])); ?>
                        <?php echo $this->getReviewsSummaryHtml($this->getProduct(), 'short', true) ?>
                        <?php Mage::unregister('ave40_instance_product_items_block'); ?>


                        <div class="parameter" id="ave40_attributes_list">
                            <?php /* 优惠金额 */ ?>
                            <div class="discount-price">
                                <span class="words"><?php echo __t('Price') ?>:</span>
                                <div class="sales-price" id="price_label">
                                    <?php echo $this->getCoreHelper()->currency($this->getProductFinalPrice(), true, false); ?>
                                </div>

                                <?php if (!$this->getAve40CustomerHelper()->isWholesaleUser()
                                    && $this->getProductFinalPrice() != $this->getProduct()->getPrice()): ?>
                                    <div class="old-price">
										<span class="price">
											<?php echo $this->getCoreHelper()->formatPrice($this->getProduct()->getData('price')) ?>
										</span>
                                    </div>
                                <?php endif; ?>

                                <?php if (!$this->getAve40CustomerHelper()->isWholesaleUser()
                                    && $this->getProductFinalPrice() != $this->getProduct()->getPrice()): ?>
                                    <div class="off">
										<span class="off-text">
											<span id="ave40_off_label">
												- <?php echo $this->getDiscountPercent() ?></span>
											%</span>
                                    </div>
                                <?php endif ?>
                            </div>

                            <?php /* 价格 */ ?>
                            <?php if ($this->getProductFinalPrice() != $this->getProduct()->getPrice()): ?>
                                <div class="old-price hidden">
                                    <span class="words"><?php echo __t('Price') ?>:</span>
                                    <span class="price">
										<?php echo $this->getCoreHelper()->formatPrice($this->getProduct()->getData('price')) ?>
									</span>
                                </div>
                            <?php endif; ?>

                            <?php echo $this->getProductTierPriceHtml() ?>

                            <?php /* MSRP */ ?>
                            <?php if ($this->getAve40CustomerHelper()->isWholesaleUser() && $this->getProduct()->getData('msrp')): ?>
                                <div class="msrp-price-col">
                                    <span class="words">Msrp: </span>
                                    <div class="msrp-price-info">
                                        <span class="msrp-value" id="msrp_value">
											<?php echo $this->getCoreHelper()->currency($this->getProduct()->getData('msrp'), true, false); ?>
										</span>
                                        <span class="msrp-discount-percent">
                                            <span>Discount:</span>
                                            <span id="msrp_discount_percent">
												-<?php echo $this->getDiscountPercent($this->getProductFinalPrice(), $this->getProduct()->getData('msrp')) ?>%
											</span>
                                        </span>
                                    </div>
                                </div>
                            <?php endif ?>

                            <?php echo $this->getChildHtml('product_type_data') ?>

                            <?php $typeInstance = $this->getProduct()->getTypeInstance(true); ?>
                            <div class="stock_left" id="qty-show" data-pmap='<?= json_encode($pmap)?>'>
                                <?php if ($rqty <= 200 && $rqty > 0): ?>
                                    <!--<div>Only <span></span> left</div>-->
                                <?php endif ?>
                            </div>
                            <?php if($this->getAve40CustomerHelper()->isWholesaleUser() && $this->getProduct()->getTypeId() == 'configurable'): ?>
                                <?php $this->outputBulkChoiceHtml() ?>
                            <?php else: ?>
                                <?php $this->outputAttributeSelectHtml() ?>
                            <?php endif; ?>

                            <?php $customerHelper = Mage::helper('ave40_base/customer');?>
                            <?php if (Mage::getSingleton('customer/session')->getCustomer()->getGroupId() != 2): ?>

                                <?php if (!$customerHelper->isLoginned()): ?>
                                    <div class="veri-bewholesale clearfix">
                                        <a href="/customer/account/create/" class="no_verification_submit_login" target="_parent">Register</a>
                                        <span><em class="fontsize-red">* </em>Register a wholesale account to view our tier pricing table.</span>
                                    </div>
                                <?php else: ?>
                                    <div class="veri-bewholesale clearfix">
                                        <a href="javascript:;" class="no_verification_submit">Verification</a>
                                        <span><em class="fontsize-red">* </em>Become a wholesaler to view our tier pricing table.</span>
                                    </div>
                                <?php endif ?>

                            <?php endif; ?>

                        </div>
                    <?php endif;/* onlyshow */ ?>
                </div>
            </form>
        </div>
    </div> <!-- 产品详细信息 end -->
    <?php echo $this->getChildHtml('inquire_form') ?>

    <?php /* VLADDIN 一款产品特殊显示提示 */ ?>
    <?php if (!empty($this->getProduct()->getId()) && $this->getProduct()->getId() == '320323'):?>
        <div class="normal_tips">
            <i class="normal_tips-icon"></i>
            <div class="normal_tips-text">
                <h3>To our valued customers in USA:</h3>
                <p>This product cannot sell to the USA. Please think twice before putting it to your shopping cart.</p>
            </div>
        </div>
    <?php endif; ?>
    <!--Key words-->
    <?php echo $this->getChildHtml('product_view.keyword') ?>
</div>

<?php /*倒计时脚本*/ ?>
<script type="text/javascript">
    <?php if ($this->getProduct()->getSpecialPrice() && $this->getProduct()->getSpecialToDate()): ?>
    countDown("<?=$this->getProduct()->getSpecialToDate()?>", ".time .day", ".time .hour", ".time .minute", ".time .second");
    <?php endif ?>
</script>


<script>
    ~function ($) {
        window.parent.ave40.closeLoading();

        $(function () {
            // 调用父元素方法弹出快速弹窗
            window.parent.showQuickViewWin();

            $('.no_verification_submit').click(function () {
                //iframe子页面调用父页面方法
                window.parent.quickViewVerification();
            });

            $('.quickViewPopup .addToCart  #add-to-cart-btn').removeAttr('onclick').on('click',function () {
                productAddToCartForm.submit(this, null, true, function (result) {
                    window.parent.closequickViewWin();
                    window.parent.updateTopCartInfo(result);
                    window.parent.Ave40MessageBox.alertSuccess('Successfully joined the shopping cart');
                });
            });

            // iframe快速购买加入购物车操作
            $('.quickViewPopup .bulk-add-to-cart #add-to-cart-btn').attr('data-quick-view','true');

        })
    }(jQuery)
</script>
