<div class="search-no-word">
	<img src="<?php echo $this->getSkinUrl('images/search/cloud-01.png') ?>" class="clound-01" alt="">
	<img src="<?php echo $this->getSkinUrl('images/search/cloud-02.png') ?>" class="clound-02" alt="">
	<img src="<?php echo $this->getSkinUrl('images/search/cloud-03.png') ?>" class="clound-03" alt="">
	<!--<span class="inquireNow">--><?php //echo Mage::helper("Ave40_Translate")->__('Inquire now') ?><!--</span>-->
	<?php //echo $this->getChild('inquire_form')->toHtml() ?>
</div>