<div class="giveaways-page imgCenterPosition">
        <img src="<?= $this->getSkinUrl('images/topic/giveaways_01.jpg') ?>" alt="">
        <img src="<?= $this->getSkinUrl('images/topic/giveaways_02.jpg') ?>" alt="">
        <img src="<?= $this->getSkinUrl('images/topic/giveaways_03.jpg') ?>" alt="">
        <div class="giveaways-step2">
            <a href="mailto:info@ave40.com" title="click to send email" class="open-email"></a>
            <img src="<?= $this->getSkinUrl('images/topic/giveaways_04.jpg') ?>" alt="">
        </div>
        <div class="giveaways-step3">
            <img src="<?= $this->getSkinUrl('images/topic/giveaways_05.jpg') ?>" alt="">
            <!-- Go to www.addthis.com/dashboard to customize your tools -->
            <div class="addthis_inline_share_toolbox_568p"></div>
        </div>
        <img src="<?= $this->getSkinUrl('images/topic/giveaways_06.jpg') ?>" alt="">
</div>
<!-- Go to www.addthis.com/dashboard to customize your tools --> <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-58fefb0c3bbf5bfe"></script>

<script type="text/javascript">
    var addthis_config = {"data_track_addressbar":false};
    var addthis_share = {
        url: "https://www.ave40.com/limitless-200w-box-mod.html",
        title: "Original Limitless LMC 200W Box Mod New Color 20% Off Stock Offer - AVE40.COM",
        description: "Where to buy best Limitless LMC 200W Box Mod New Color. AVE40 is the only vapor company worldwide where you can purchase this new 200W MOD. 20% off for new member is really appealing!",
        media: "https://www.ave40.com/media/catalog/product/cache/1/thumbnail/500x/9df78eab33525d08d6e5fb8d27136e95/l/i/limitless-200w-box-mod-9.jpg"
    }
</script>