<div class="affiliate-program-page">
	<div class="aff-pro-1-col">
		<img src="{{skin url='images/homepage/affiliate/g_02.jpg'}}" alt="">
		<img src="{{skin url='images/homepage/affiliate/g_03.jpg'}}" alt="">
		<img src="{{skin url='images/homepage/affiliate/g_04.jpg'}}" alt="">
		<img src="{{skin url='images/homepage/affiliate/g_05.jpg'}}" alt="">
	</div>

	<div class="aff-pro-2-col">
		<img src="{{skin url='images/homepage/affiliate/g_06.jpg'}}" alt="">
		<a href="http://www.flexoffers.com/affiliate-programs/ave40-e-cigarettes-affiliate-program/" target="_blank" class="aff-pro-join-btn">
			<img src="{{skin url='images/homepage/affiliate/join-now.png'}}" alt="">
		</a>
	</div>

	<div class="aff-pro-asked-col">
		<h2>Frequently Asked Questions</h2>
		<ul class="aff-pro-asked-list">
			<li class="aff-pro-asked-li">
				<div class="aff-pro-asked-title">
					<i class="aff-pro-asked-icon"></i>
					<span>Why Choose Ave40?</span>
				</div>
				<ol class="aff-pro-asked-answer">
					<li><span>We are a leading B2B / B2C platform expert in wholesale business in E-cigarettes, E-liquids and accessories. </span></li>
					<li><span>We have a lot of exclusive products, and we maintain a very close relationship with all our manufacturers.</span></li>
					<li><span>We have over 4-year experience in the Vape industry.</span></li>
					<li><span>We take care of our customers and we are working hard every day to provide them the best products.</span></li>
				</ol>
			</li>
			<li class="aff-pro-asked-li">
				<div class="aff-pro-asked-title">
					<i class="aff-pro-asked-icon"></i>
					<span>Is there any fee to become an affiliate?</span>
				</div>
				<p class="aff-pro-asked-answer-p">The AVE40 affiliate program is 100% free, please join us !!!</p>
			</li>
			<li class="aff-pro-asked-li">
				<div class="aff-pro-asked-title">
					<i class="aff-pro-asked-icon"></i>
					<span>Is there any skills needed to be your affiliate?</span>
				</div>
				<p class="aff-pro-asked-answer-p">No, you just need to <a href="https://publisherpro.flexoffers.com/registration" target="_blank">register</a> your website in Flexoffers and accept our campaign. Flexoffers will detect automatically when one customer will purchase some products from your website.</p>
			</li>
			<li class="aff-pro-asked-li">
				<div class="aff-pro-asked-title">
					<i class="aff-pro-asked-icon"></i>
					<span>How do I get the AVE40 affiliate links?</span>
				</div>
				<p class="aff-pro-asked-answer-p">Log in to Flexoffers.com and search for AVE40. Flexoffers will provide to you some basic widgets.</p>
			</li>
			<li class="aff-pro-asked-li">
				<div class="aff-pro-asked-title">
					<i class="aff-pro-asked-icon"></i>
					<span>Is the Ave40 affiliate marketing program transparent?</span>
				</div>
				<p class="aff-pro-asked-answer-p">We take care of our affiliates in the same way as we do with our customers. Flexoffers will inform you as soon as possible once the customers purchase a product in our website. </p>

			</li>
			<li class="aff-pro-asked-li">
				<div class="aff-pro-asked-title">
					<i class="aff-pro-asked-icon"></i>
					<span>If someone I refer places their order 1 week later, will that order still track back to me?</span>
				</div>
				<p class="aff-pro-asked-answer-p">Yes, our default referral period is 30 days. Don’t worry and enjoy now our affiliate marketing program.</p>
			</li>

			<li class="aff-pro-asked-li">
				<div class="aff-pro-asked-title">
					<i class="aff-pro-asked-icon"></i>
					<span>How will I get my commission?</span>
				</div>
				<p class="aff-pro-asked-answer-p">Your commission will be paid directly by Flexoffers.</p>
			</li>
			<li class="aff-pro-asked-li contact-us">
				<div class="aff-pro-asked-title ">
					<span>Contact us:</span>
				</div>
				<p class="aff-pro-asked-answer-p">If you have any kind of questions, please feel free to ask us at business@ave40.com.</p>
			</li>
		</ul>
	</div>

</div>