<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/21
 * Time: 下午 4:57
 */

/* @var Ave40_Catalog_Block_Product_Items $this */
$_productCollection = $this->getProductCollection();
/** @var Ave40_Base_Helper_Customer $customerHelper */
$customerHelper = Mage::helper('ave40_base/customer');

$vars = [
    'only_list' => !!$this->getData('only_list'),
    'special_countdown' => !!$this->getData('special_countdown'),
    'mouse_over_tools' => !!(($this->getData('mouse_over_tools')===null) ? true : $this->getData('mouse_over_tools')),
    'enable_pagination' => $this->getData('enable_pagination'),
    'display_aslowas_price' => !!(($this->getData('display_aslowas_price')==null) ? true : $this->getData('display_aslowas_price')),
];

if($vars['special_countdown']):
    $__isOutOfSpecialDate = function($product) {
        $fromDate = $product->getSpecialFromDate();
        $toDate = $product->getSpecialToDate();
        $now = time();

        return $now < strtotime($fromDate) || $now > strtotime($toDate);
    };

    $__calcDetailTwoDate = function ($start, $end) {
        $start = is_numeric($start) ? $start : strtotime($start);
        $end = is_numeric($end) ? $end : strtotime($end);
        $dvalue = $end - $start;

        $days=0;
        $hours=0;
        $minutes=0;
        $seconds=0;

        if($dvalue > 0) {
            $minSeconds = 60;
            $hourSeconds = 60 * $minSeconds;
            $daySecond = 24 * $hourSeconds;

            $days = floor ($dvalue / $daySecond);
            $dvalue -= $days * $daySecond;
            $hours = floor( $dvalue / $hourSeconds);
            $dvalue -= $hours * $hourSeconds;
            $minutes = floor( $dvalue / $minSeconds);
            $dvalue -= $minutes * $minSeconds;
            $seconds = $dvalue;
        }

        $result = compact(explode(' ', 'days hours minutes seconds'));
        $result['start_time'] = $start;
        $result['end_time'] = $end;
        return $result;
    };

    $__getProductSpecialDateDetail = function ($product) use ($__calcDetailTwoDate) {
        $toDate = $product->getSpecialToDate();
        $now = time();

        return $__calcDetailTwoDate($now, $toDate);
    };
endif; /* special_countdown is enabled */

$imageSize = $this->getImageSize();
$imageWidth = 170;
$imageHeight = 170;

if(!empty($imageSize)) {
    list($_width, $_height) = explode(',', $imageSize);

    if(!(empty($_width) && empty($_height))) {
        $_width = empty($_width) ? $_height : $_width;
        $_height = empty($_height) ? $_width : $_height;
        $imageWidth = intval($_width);
        $imageHeight = intval($_height);
    }
}

Mage::unregister('current_category');

$count = count($_productCollection->getItems());
$rowsPerPage = 6;
$index = 0;
?>

<?php foreach ($_productCollection as $_product): ?>
<?php if($index == 0 || $index % $rowsPerPage == 0): ?>
<div class="swiper-slide">
    <ul class="product-items home-list product_item_wrap clearfix">
<?php endif; ?>

        <li class="item product_item_box" product_id="<?php echo $_product->getId()?>" product_type="<?php echo $_product->getTypeId() ?>" >
            <div class="product_item_card clearfix">
                <div class="product_card_img">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imageWidth, $imageHeight) ?>"
                             srcset="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imageWidth * 2, $imageHeight * 2) ?> 2x"
                             alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                    </a>
                </div>
                <div class="product_card_other_info">
                    <?php if($vars['mouse_over_tools']): ?>
                        <?php Mage::unregister('ave40_instance_product_items_block'); ?>
                        <?php Mage::register('ave40_instance_product_items_block', $this); ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short', true) ?>
                        <?php Mage::unregister('ave40_instance_product_items_block'); ?>
                    <?php endif; ?>
                    <h2 class="product_card_name">

                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                            <?php if($_product->getFinalPrice() && $_product->getFinalPrice() < $_product->getPrice()):?>
                                <?php $discountPercent =  ceil(round(($_product->getPrice() - $_product->getFinalPrice()) / $_product->getPrice(), 2) * 100) ?>
                                <?php /* 折扣标签  */ ?>
                                <i class="sales_label">-<?php echo $discountPercent ?>%</i>
                            <?php endif; ?>
                            <?php echo $this->htmlEscape($_product->getName()) ?>
                        </a>
                    </h2>

                    <?php $canShowMsrp = $customerHelper->getIsGuidePageCustomer() || $customerHelper->isLoginAsWholesales() ?>
                    <?php $hasMsrp = $_product->getMsrp()?>
                    <div class="product_card_price <?php echo $hasMsrp && $canShowMsrp ? 'show_msrp_price clearfix' : '' ?>">
                        <?php if($canShowMsrp): ?>
                            <?php if($_product->getMsrp()): ?>
                                <div class="msrp-price">MSRP<span><?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() ?><?php echo sprintf('%.2f', round($_product->getMsrp(), 2)) ?></span>
								</div>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php echo $this->getPriceHtml($_product, $vars['display_aslowas_price'], $this->getPriceSuffix()) ?>
					</div>

                    <?php $canShowFreeShippingLabel = $customerHelper->getIsGuidePageCustomer() || $customerHelper->isLoginAsWholesales() ?>
                    <?php if(!$canShowFreeShippingLabel): ?>
						<!-- free shipping 标签 -->
						<div class="free_shipping_label">FREE SHIPPING</div>
                    <?php endif; ?>

					<!-- 产品标签模块 -->
					<div class="product_card_label_box">
						<div class="tpd_and_exclusive_label_box">

							<?php /* Exclusive标签  */ ?>
							<?php
							/** @var Ave40_Base_Helper_Globalcate $glcatehelper */
							$glcatehelper = Mage::helper('ave40_base/globalcate');
							?>
							<?php if($glcatehelper->isExclusiveProduct($_product->getId())): ?>
								<i class="exclusive_label">EXCLUSIVE</i>
							<?php endif; ?>

							<?php /* TPD标签  */ ?>
							<?php if ($_product->getData('tpd')): ?>
								<i class="tpd_label" title="TPD compliance" >
									<?php echo Mage::helper("Ave40_Translate")->__('TPD') ?>
								</i>
							<?php endif ?>
						</div>

						<?php /*Pre-order标签  */ ?>
						<?php if ($_product->getData('pre_sales')): ?>
							<?php $pre_arrival_date = strtotime($_product->getData('pre_arrival_date'));?>
							<?php if (!($pre_arrival_date && $pre_arrival_date < time())): ?>
								<i class="pre_order_label">PRE-ORDER</i>
							<?php endif ?>
						<?php endif ?>

					</div>


                    <div class="quickView"><img src="<?= $this->getSkinUrl('images/product/chakan.png') ?>" alt="">QUICK VIEW</div>

                    <div class="clear"></div>
                </div>


            </div>
        </li>
<?php if(($index+1) % $rowsPerPage == 0 || $index == $count-1): ?>
    </ul>
</div>
<?php endif; ?>

    <?php $index ++; ?>
<?php endforeach; ?>

<?php if($vars['enable_pagination']): ?>
    <?php
    /* @var Ave40_Widget_Block_Pagination	$block */
    $block = Mage::app()->getLayout()->createBlock('ave40_widget/pagination');
    $urlPageKey = $this->getPaginationUrlKey() ? $this->getPaginationUrlKey() : 'page';
    $block->setUrlQueryKey($urlPageKey);
    $block->setCurrentPage($_GET[$urlPageKey] <= 0 ? 1 : $_GET[$urlPageKey]);
    $block->setLastPage($_productCollection->getLastPageNumber());
    $block->outputHtml();
    ?>
<?php endif; ?>



