<?php if (($_products = $this->getProductCollection()) && $_collectionSize = $_products->getSize()): ?>
<div class="featured-cat-block home-box">
	<div class="content  catalog-listing bmproducts-latest">
		<ul class="home-list">
			<?php foreach ($_products->getItems() as $_product): ?>
			<li class="item" product_id="<?=$_product->getId()?>">
				<div class="home-product-img">
					<a href="<?=$_product->getProductUrl()?>" title="<?=$this->htmlEscape($_product->getName())?>">
						<img class="lazy" data-original="<?=$this->helper('catalog/image')->init($_product, 'small_image')->resize(170, 170)?>"
							 src="<?php echo $this->getData('only_list') ? $this->helper('catalog/image')->init($_product, 'small_image')->resize(170, 170) : $this->getSkinUrl('images/loader.gif'); ?>"
							 alt="<?=$this->htmlEscape($_product->getName())?>" width="170" style="display: inline;">
					</a>
				</div>
				<div class="product-other-info">
					<?php echo $this->getReviewsSummaryHtml($_product, 'short', true) ?>
					<h2 class="product-name">
						<a href="<?=$_product->getProductUrl()?>" title="<?=$this->htmlEscape($_product->getName())?>">
							<?=$this->htmlEscape($_product->getName())?>
						</a>
					</h2>
					<div class="price-box">
						<span class="sales-price" id="product-price-<?=$_product->getId()?>-latest">
								<span class="price">$<?=number_format($_product->getSpecialPrice() ? $_product->getSpecialPrice() : $_product->getPrice(), 2)?></span>
						</span>
						<?php if ($_product->getSpecialPrice() && ($_product->getPrice() > $_product->getSpecialPrice())): ?>
						<span class="old-price" id="product-price-<?=$_product->getId()?>-latest">
							<span class="price">$<?=number_format($_product->getPrice(), 2)?></span>
						</span>
						<?php endif ?>
					</div>
				</div>
				<?php if ($_product->getSpecialPrice() && ($_product->getPrice() > $_product->getSpecialPrice())): ?>
				<div class="off">
					<span class="off-text"><?=intval(($_product->getPrice()-$_product->getSpecialPrice())*100/$_product->getPrice())?>% OFF</span>
				</div>
				<?php endif ?>
				<div class="clear"></div>
			</li>
			<?php endforeach; ?>
		</ul>
	</div>
	<script type="text/javascript">
		jQuery(function () {
			decorateGeneric($$('.grid-row'), ['first', 'last', 'odd', 'even']);
		})

	</script>
</div>
<?php endif; ?>
<div class="clear"></div>
