<div id="subscribe">
	<div class="tips">
		<?php echo Mage::helper("Ave40_Translate")->__('Always faster than others, to deliver lastest info to clients.') ?>
	</div>
	<form  id="newsletter-validate-detail">
		<div class="subscribe_box">
			<input type="email" name="email" id="newsletter" class="subscribe_input" required="required" />
			<input type="submit" class="subscribe_btn" value="<?php echo Mage::helper("Ave40_Translate")->__('Subscribe') ?>" />
		</div>
	</form>
</div>

