<div class="top-myaccount">
	<div class="top-myaccount-header">
		<a  rel="nofollow"   id="top-myaccount"  href="<?php echo $this->getUrl('customer/account') ?>" title="My Account"><?php echo Mage::helper("Ave40_Translate")->__('My Account') ?></a>
		<span class="top_arrow"></span>
	</div>
	<div class="drop-menu" style="display:none;">
		<a  rel="nofollow"   id="top-mydashboard"  href="<?php echo $this->getUrl('customer/account') ?>" title="My Dashboard"><?php echo Mage::helper("Ave40_Translate")->__('Account Dashboard') ?></a>
		<a  rel="nofollow"   id="top-mywishliist"  href="<?php echo $this->getUrl('wishlist') ?>" title="My Wishlist"><?php echo Mage::helper("Ave40_Translate")->__('My Wishlist') ?></a>
		<a  rel="nofollow"   id="top-myorder"  href="<?php echo $this->getUrl('sales/order/history') ?>" title="My Order"><?php echo Mage::helper("Ave40_Translate")->__('My Order') ?></a>
		<a  rel="nofollow"   id="top-myreviews"  href="<?php echo $this->getUrl('review/customer') ?>" title="My Reviews"><?php echo Mage::helper("Ave40_Translate")->__('My Product Reviews') ?></a>
		<a  rel="nofollow"   id="top-mytags"  href="<?php echo $this->getUrl('tag/customer') ?>" title="My Tags"><?php echo Mage::helper("Ave40_Translate")->__('My Tags') ?></a>
	</div>
</div>