<?php
/**
 * Temlate for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>
<div class="page-title title-buttons">
	<h1><?php echo Mage::helper("Ave40_Translate")->__('Address Book') ?></h1>
	<button type="button" title="<?php echo Mage::helper("Ave40_Translate")->__('Add New Address') ?>" class="button" onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><span><span><?php echo Mage::helper("Ave40_Translate")->__('Add New Address') ?></span></span></button>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="col2-set addresses-list">
	<div class="col-1 addresses-primary">
		<h2><?php echo Mage::helper("Ave40_Translate")->__('Default Addresses') ?></h2>
		<ol>
		<?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
			<li class="item">
				<h3><?php echo Mage::helper("Ave40_Translate")->__('Default Billing Address') ?></h3>
				<address>
					<?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
				</address>
				<p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo Mage::helper("Ave40_Translate")->__('Change Billing Address') ?></a></p>
		   </li>
		<?php else: ?>
			<li class="item">
				<h3><?php echo Mage::helper("Ave40_Translate")->__('Default Billing Address') ?></h3>
				<?php echo Mage::helper("Ave40_Translate")->__('You have no default billing address in your address book.') ?>
			</li>
		<?php endif ?>

		<?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
			<li class="item">
				<h3><?php echo Mage::helper("Ave40_Translate")->__('Default Shipping Address') ?></h3>
				<address>
					<?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
				</address>
				<p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo Mage::helper("Ave40_Translate")->__('Change Shipping Address') ?></a></p>
			</li>
		<?php else: ?>
			<li class="item empty">
				<h3><?php echo Mage::helper("Ave40_Translate")->__('Default Shipping Address') ?></h3>
				<p><?php echo Mage::helper("Ave40_Translate")->__('You have no default shipping address in your address book.') ?></p>
			</li>
		<?php endif ?>
		</ol>
	</div>
	<div class="col-2 addresses-additional">
		<h2><?php echo Mage::helper("Ave40_Translate")->__('Additional Address Entries') ?></h2>
		<ol>
		<?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
			<?php foreach($_pAddsses as $_address): ?>
			<li class="item">
				<address>
					<?php echo $this->getAddressHtml($_address) ?>
				</address>
				<p><a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo Mage::helper("Ave40_Translate")->__('Edit Address') ?></a> <span class="separator">|</span> <a href="#" class="link-remove" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo Mage::helper("Ave40_Translate")->__('Delete Address') ?></a></p>
			</li>
			<?php endforeach; ?>
		<?php else: ?>
			<li class="item empty">
				<p><?php echo Mage::helper("Ave40_Translate")->__('You have no additional address entries in your address book.') ?></p>
			</li>
		<?php endif ?>
		</ol>
	</div>
</div>
<!--
<div class="buttons-set">
	<p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo Mage::helper("Ave40_Translate")->__('Back') ?></a></p>
</div>
-->
<script type="text/javascript">
//<![CDATA[
	function deleteAddress(addressId) {
		if(confirm('<?php echo Mage::helper("Ave40_Translate")->__('Are you sure you want to delete this address?') ?>')) {
			window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
		}
		return false;
	}
//]]>
</script>
