<?php
/**
 * Edit customer address template
 *
 * @see Mage_Customer_Block_Address_Edit
 */
?>
<?php if($this->getTitle()): ?>
<div class="add-address-pop">

	<?php endif; ?>
	<?php echo $this->getMessagesBlock()->toHtml() ?>
	<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate">
		<div class="fieldset">
		<?php echo $this->getBlockHtml('formkey')?>
		<input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
		<input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
			<ul class="form-list">
				<li class="fields">
					<?php echo $this->getNameBlockHtml() ?>
				</li>
				<li class="wide">
					<label for="company"><?php echo $this->__('Company') ?></label>
					<div class="input-box">
						<input type="text" name="company" id="company" title="<?php echo $this->__('Company') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
					</div>
				</li>
				<li class="fields">
					<div class="field telephone-field">
						<label for="telephone" class="required"><span class="asterisk">*</span><?php echo $this->__('Telephone') ?></label>
						<div class="input-box">
							<input type="text" name="telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text  <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" />
						</div>
					</div>
					<div class="field fax-field">
						<label for="fax"><?php echo $this->__('Fax') ?></label>
						<div class="input-box">
							<input type="text" name="fax" id="fax" title="<?php echo $this->__('Fax') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" />
						</div>
					</div>
				</li>
			</ul>
		</div>
		<div class="fieldset street">
			<ul class="form-list">
			<?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
				<li class="wide">
					<label for="street_1" class="required"><span class="asterisk">*</span><?php echo $this->__('Street Address') ?></label>
					<div class="input-box">
						<input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" placeholder="<?php echo Mage::helper("Ave40_Translate")->__('Street Address') ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
					</div>
				</li>
			<?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
			<?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
				<li class="wide">
					<div class="input-box">
						<input type="text" name="street[]" placeholder="<?php echo Mage::helper("Ave40_Translate")->__('Apartment,Suit,Unit(etc)') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
					</div>
				</li>
			<?php endfor; ?>
				<?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
				<li class="wide">
					<label for="vat_id"><?php echo $this->__('VAT Number') ?></label>
					<div class="input-box">
						<input type="text" name="vat_id" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" id="vat_id" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
					</div>
				</li>
				<?php endif; ?>
				<li class="fields city-state-fields">
					<div class="field">
						<!--<label for="city" class="required"><em>*</em><?php /*echo $this->__('City') */?></label>-->
						<div class="input-box">
							<input type="text" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" placeholder="<?php echo Mage::helper("Ave40_Translate")->__('City') ?>"  title="<?php echo $this->__('City') ?>" class="input-text add-new-city <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
						</div>
					</div>
					<div class="field">
						<!--<label for="region_id" class="required"><em>*</em><?php /*echo $this->__('State/Province') */?></label>-->
						<div class="input-box">
							<select id="region_id" name="region_id"  title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
							   <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
							</select>
							<script type="text/javascript">
							//<![CDATA[
								$('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
							//]]>
							</script>
							<input type="text" id="region" name="region" placeholder="<?php echo Mage::helper("Ave40_Translate")->__('State/Province') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text add-new-state <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
						</div>
					</div>
				</li>
				<li class="fields zip-country">
					<div class="field">
						<!--<label for="zip" class="required"><em>*</em><?php /*echo $this->__('Zip/Postal Code') */?></label>-->
						<div class="input-box">
							<input type="text" name="postcode" placeholder="<?php echo Mage::helper("Ave40_Translate")->__('Zip/Postal Code') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text add-new-ZipCode validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
						</div>
					</div>
					<div class="field">
						<!--<label for="country" class="required"><em>*</em><?php /*echo $this->__('Country') */?></label>-->
						<div class="input-box">
							<?php echo $this->getCountryHtmlSelect() ?>
						</div>
					</div>
				</li>
				<!--<li<?php /*if($this->canSetAsDefaultBilling()) echo ' class="control"' */?>>
					<?php /*if($this->isDefaultBilling()): */?>
						<strong><?php /*echo $this->__('Default Billing Address') */?></strong>
					<?php /*elseif($this->canSetAsDefaultBilling()): */?>
						<input type="checkbox" id="primary_billing" name="default_billing" value="1" title="<?php /*echo $this->__('Use as My Default Billing Address') */?>" class="checkbox" /><label for="primary_billing"><?php /*echo $this->__('Use as my default billing address') */?></label>
					<?php /*else: */?>
						<input type="hidden" name="default_billing" value="1" />
					<?php /*endif; */?>
				</li>-->
				<li<?php if($this->canSetAsDefaultShipping()) echo ' class="control"' ?>>
					<?php if($this->isDefaultShipping()): ?>
						<strong><?php echo $this->__('Default Shipping Address') ?></strong>
					<?php elseif($this->canSetAsDefaultShipping()): ?>
						<input type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?php echo $this->__('Use as My Default Shipping Address') ?>" class="checkbox" /><label for="primary_shipping"><?php echo $this->__('Use as my default shipping address') ?></label>
					<?php else: ?>
						<input type="hidden" name="default_shipping" value="1" />
					<?php endif; ?>
				</li>
			</ul>
		</div>
		<div class="buttons-set">
			<!--
			<p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><?php echo $this->__('<< Back') ?></a></p>
			-->
			<button id="save_address_btn" data-action="save-customer-address" type="submit" title="<?php echo $this->__('Save Address') ?>" class="button add-new-submit"><span><span><?php echo $this->__('Save Address') ?></span></span></button>
            <button id="cancel_address_btn"  type="button" title="<?php echo $this->__('Cancel') ?>" class="button cancel_address_btn"><span><span><?php echo $this->__('Cancel') ?></span></span></button>

        </div>
		<input type="hidden" name="ajax" value="1">
	</form>
</div>
<script type="text/javascript">
	<?php if (!empty($_GET['id'])): ?>
		jQuery('.add-address-pop').show();
	<?php endif ?>

	var dataForm = new VarienForm('form-validate', true);
	new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
	jQuery('#form-validate').submit(function(e){
		var evt = e || window.event;
		evt.preventDefault();
		jQuery.ajax({
			url: jQuery('#form-validate').attr('action'),
			type: 'post',
			data: jQuery('#form-validate').serialize(),
			dataType: 'json',
			success: function (result) {
				if (result.errno) {
					alert(result.errmsg);
					return;
				}
				<?php if (empty($_GET['id'])): ?>
				location.reload();
				<?php else: ?>
				location.href = '/customer/account/#address';
				<?php endif ?>
			},
			error: function () {
			}
		});
	});


</script>
