<?php /* @var $this Mage_Captcha_Block_Captcha_Zend */ ?>

<?php /* @var $captcha Mage_Captcha_Model_Zend */ ?>
<?php $captcha = $this->getCaptchaModel() ?>

<input type="text" class="captacha" required="required"  name="<?php echo Mage_Captcha_Helper_Data::INPUT_NAME_FIELD_VALUE ?>[<?php echo $this->getFormId()?>]" id="captcha_<?php echo $this->getFormId() ?>" />
<span class="code">
	<img id="<?php echo $this->getFormId() ?>" class="captcha-img" _width="<?php echo $this->getImgWidth() ?>" _height="<?php echo $this->getImgHeight() ?>" src="<?php echo $captcha->getImgSrc().'/formId/'.$this->getFormId(); ?>" alt="<?php echo Mage::helper("Ave40_Translate")->__('Reload captcha') ?>" title="Click picture to refresh" onclick="$('<?php echo $this->getFormId()?>').captcha.refresh(this)"/>
</span>
<script type="text/javascript">
	$('<?php echo $this->getFormId() ?>').captcha = new Captcha('<?php echo $this->getRefreshUrl() ?>', '<?php echo $this->getFormId() ?>');
</script>

<!--
<li id="captcha-input-box-<?php echo $this->getFormId()?>">
	<label for="captcha_<?php echo $this->getFormId() ?>" class="required"><em>*</em><?php echo Mage::helper("Ave40_Translate")->__('Please type the letters below')?></label>
	<div class="input-box captcha">
		<input name="<?php echo Mage_Captcha_Helper_Data::INPUT_NAME_FIELD_VALUE ?>[<?php echo $this->getFormId()?>]" type="text" class="input-text required-entry" id="captcha_<?php echo $this->getFormId() ?>" />
	</div>
</li>
<li>
	<div class="captcha-image" id="captcha-image-box-<?php echo $this->getFormId()?>">
		<img id="captcha-reload" class="captcha-reload" src="<?php echo $this->getSkinUrl('images/reload.png') ?>" alt="<?php echo Mage::helper("Ave40_Translate")->__('Reload captcha') ?>" onclick="$('<?php echo $this->getFormId()?>').captcha.refresh(this)">
		<img id="<?php echo $this->getFormId() ?>" class="captcha-img" height="<?php echo $this->getImgHeight() ?>" src="<?php echo $captcha->getImgSrc() ?>"/>
		<?php if ($captcha->isCaseSensitive()) :?>
		<div class="captcha-note">
			<?php echo Mage::helper("Ave40_Translate")->__('<strong>Attention</strong>: Captcha is case sensitive.') ?>
		</div>
		<?php endif; ?>
	</div>
	<script type="text/javascript">//<![CDATA[
		$('<?php echo $this->getFormId() ?>').captcha = new Captcha('<?php echo $this->getRefreshUrl() ?>', '<?php echo $this->getFormId() ?>');
	//]]></script>
</li>
-->

