<?php
/**
 * @var Ave40_Review_Block_Customer_List $this
 */

$subpage = strtolower(Mage::app()->getRequest()->getParam('sp'));
$subpageKeys = ['reviewed', 'notreview'];
$subpage = in_array($subpage, $subpageKeys) ? $subpage : $subpageKeys[0];
$GLOBALS['___subpage'] = $subpage;

$currency = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
//$page = Mage::app()->getRequest()->getParam('page', 1);
//$page = $page <= 0 ? 1 : $page;


function checkClass($matchkey)
{
	return $matchkey == $GLOBALS['___subpage'] ? 'active' : '';
}

?>
<style>
	.busying {
		opacity: 0.5 !important;
		cursor: wait !important;
	}
</style>

<?php if(Mage::helper('ave40_widget')->getDeviceDetector()->isMobile()): ?>
    <style>
        .personal-aside{
            display: none;
        }
    </style>
<?php endif; ?>

<div class="personal-main">
	<div class="main-right review-main">
		<div class="main-tab">
			<ul class="tab" data-taboff>
				<li class="<?php echo checkClass('reviewed') ?>"><a href="?sp=reviewed"><span><?php echo Mage::helper("Ave40_Translate")->__('Reviewed') ?></span></a></li>
				<li class="<?php echo checkClass('notreview') ?>"><a href="?sp=notreview"><span><?php echo Mage::helper("Ave40_Translate")->__('Not reviewed') ?></span></a></li>
			</ul>
		</div>
		<?php if ($subpage == 'notreview'): ?>
			<!-- not-review选项卡 -->
			<div class="tab-main-content not-review" data-page="1">
				<?php if ($this->getNotReviewCollection()->getSize() == 0): ?>
					<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('customer/empty-list.phtml')->toHtml() ?>
				<?php else: ?>

					<div class="not-review-tab ">
						<ul class="not-review-tab-ul review-tab-common-ul clearfix">
							<li class="not-review-items"><?php echo Mage::helper("Ave40_Translate")->__('Items') ?></li>
							<li class="not-review-Credit"><?php echo Mage::helper("Ave40_Translate")->__('Price') ?></li>
							<li class="not-review-time"><?php echo Mage::helper("Ave40_Translate")->__('Time') ?></li>
							<li class="not-review-status"><?php echo Mage::helper("Ave40_Translate")->__('Operation') ?></li>
						</ul>
					</div>
					<div class="not-review-product">
						<ul class="not-review-list clearfix">
							<!-- 模板 -->
							<!--评论弹出框-->
							<div class="review-pop esc-pop popup-box">
								<form action="" id="review_form">
									<div class="pop-top clearfix">
										<div class="pop-top-userinfo user-head-img ">
											<img src="<?php echo Ave40_Api_Helper_FilesUpload::getCustomerAvatar() . "?$rand" ?>" alt="">
										</div>
										<span class="pop-top-title"><?php echo Mage::helper("Ave40_Translate")->__('Comments') ?></span>
										<span class="black-close close popup-close"></span>
									</div>
									<input type="hidden" name="item" id='item_id' />
									<div class="pop-main">
										<textarea id="comment_value" class="review-textarea" name="comment" required="required"
												  onkeydown="checkMaxInput(this,200)" onkeyup="checkMaxInput(this,200)"
												  onfocus="checkMaxInput(this,200)"
												  onblur="checkMaxInput(this,200)" required="required" aria-required="true"></textarea>
										<span class="remain-word"><i class="Max_msg">0</i>/200</span>
									</div>

                                    <!--upload review img-->
                                    <div class="review-upload-col clearfix" style="display:none ">
                                        <span class="review-upload-icon"></span>
                                        <input type="file" name="file_upload" class="up-load-input" id="review-upload-input" >
                                        <div id="queue" class="queue clearfix"></div>

                                    </div>
                                    <p class="review-upload-tip" style="display:none ">You are upload up to five</p>
									<div class="pop-footer clearfix">
										<?php foreach ($this->getRatings() as $_rating): ?>
                                            <?php if ($_rating->getId() != 4) {continue;} ?>
										<div class="ratings">
											<span class="score"><?php echo $this->escapeHtml($_rating->getRatingCode()) ?>:</span>
											<div class="star-rating clearfix">
												<ul>
													<?php foreach ($_rating->getOptions() as $_option): ?>
													<li data-value="<?php echo $_option->getId() ?>"><a href="javascript:;">&nbsp;</a></li>
													<?php endforeach; ?>
												</ul>
												<span></span>
												<p></p>
											</div>
											<input type="hidden" class="rating" name="ranting[<?php echo $_rating->getId() ?>]" value="" />
										</div>
										<?php endforeach; ?>

										<button type="submit" class="pop-submit submit-btn"><?= Mage::helper("Ave40_Translate")->__('Submit') ?></button>
									</div>
								</form>
							</div>
							<?php foreach ($this->getNotReviewCollection() as $item): ?>
								<?php
								/**
								 * @var \Mage_Catalog_Model_Product $_product
								 * @var  array $item
								 * @var Ave40_Review_Block_Customer_List $this
								 * @var Mage_Catalog_Model_Product $product
								 */
								$product = Mage::getModel('catalog/product')->load($item['product_id']);
								$productName = $this->stripTags($item['name']);
								$productImageUrl = Mage::helper('catalog/image')->init($product, 'small_image')->resize(155, 120);
								$ranting = $item->getData('rating_summary');
								$ranting = $ranting ? $ranting : 0;

                                $optionsResult = [];
                                if ($options = $item->getProductOptions()) {
                                    if (isset($options['options'])) {
                                        $optionsResult = array_merge($optionsResult, $options['options']);
                                    }
                                    if (isset($options['additional_options'])) {
                                        $optionsResult = array_merge($optionsResult, $options['additional_options']);
                                    }
                                    if (isset($options['attributes_info'])) {
                                        $optionsResult = array_merge($optionsResult, $options['attributes_info']);
                                    }
                                }
								?>
								<li class="not-review-product-info order-product-info clearfix">
									<div class="not-review-product-items">
										<div class="order-product-img">
											<img src="<?php echo $productImageUrl ?>" alt="">
										</div>
										<div class="order-product-parameter">
											<span><a href="<?php echo $product->getProductUrl() ?>"><?php echo $productName ?></a></span>
											<p class="order-color-list">
                                                <?php foreach ($optionsResult as $option): ?>
													<span class="order-product-color"><?php echo  $option['label'] ?>:</span>
													<span class="color-name"><?php echo  $option['value'] ?></span>
                                                <?php endforeach; ?>
											</p>
										</div>
									</div>
									<div class="not-review-product-credit">
										<span class="not-review-credit-word"><?php echo $currency . number_format($item->getPrice(), 2) ?></span>
									</div>
                                    <div class="not-review-product-time">
                                        <span class="not-review-credit-word"><?php echo  date('Y-m-d', strtotime($item->getCreatedAt())) ?></span>
                                    </div>
									<div class="not-review-product-status">
										<a href="javascript:;" title="" class="review-btn a-blue-under review" data-item-id="<?php echo $item['item_id'] ?>"><span><?php echo Mage::helper("Ave40_Translate")->__('Review') ?></span><div></div></a><br/>
									</div>
								</li>
							<?php endforeach; ?>
						</ul>
						<?php if ($this->getNotReviewLastPage() > 1): ?>
							<?php
							/* @var Ave40_Widget_Block_Pagination $block */
							$block = Mage::app()->getLayout()->createBlock('ave40_widget/pagination');
							$block->setLastPage($this->getNotReviewLastPage());
							$block->outputHtml();
							?>
						<?php endif; ?>
					</div>
				<?php endif; ?>
			</div>

		<?php else: ?>

			<!-- Reviewed选项卡 -->
			<div class="tab-main-content reviewed" data-page="1">
				<?php if ($this->getReviewsCollection()->getSize() == 0): ?>
					<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('customer/empty-list.phtml')->toHtml() ?>
				<?php else: ?>
					<div class="review-tab not-review-tab ">
						<ul class="review-tab-ul review-tab-common-ul not-review-tab-ul">
							<li class="review-items"><?php echo Mage::helper("Ave40_Translate")->__('Items') ?></li>
							<li class="review-avgRating"><?php echo Mage::helper("Ave40_Translate")->__('Rating') ?></li>
							<li class="review-status"><?php echo Mage::helper("Ave40_Translate")->__('Review') ?></li>
						</ul>
					</div>
					<ul class="reviewed-list not-review-list clearfix" data-cur-page="1">
						<?php foreach ($this->getReviewsCollection()->getItems() as $_reviewItem): ?>
							<?php
							/**
							 * @var  Mage_Sales_Model_Order_Item $_reviewItem
							 * @var Ave40_Review_Block_Customer_List $this
							 * @var Mage_Catalog_Model_Product $product
							 */
							$product = Mage::getModel('catalog/product')->load($_reviewItem->getEntityPkValue());
							$productName = $this->stripTags($product->getData('name'));
							$productImageUrl = Mage::helper('catalog/image')->init($product, 'small_image')->resize(155, 120);
							$color = $product->getAttributeText('color');

                            $optionsResult = [];
                            if ($options = $product->getProductOptions()) {
                                if (isset($options['options'])) {
                                    $optionsResult = array_merge($optionsResult, $options['options']);
                                }
                                if (isset($options['additional_options'])) {
                                    $optionsResult = array_merge($optionsResult, $options['additional_options']);
                                }
                                if (isset($options['attributes_info'])) {
                                    $optionsResult = array_merge($optionsResult, $options['attributes_info']);
                                }
                            }

							?>
							<li class="reviewed-product-info order-product-info clearfix" data-item-id="<?php echo $_reviewItem->getItemId() ?>">
								<div class="review-product-items">
									<div class="order-product-img">
										<img src="<?php echo $productImageUrl ?>" alt="<?php echo $productName ?>">
									</div>
									<div class="order-product-parameter">
										<a href="<?php echo $product->getProductUrl() ?>"><?php echo $productName ?></a>
										<p class="order-color-list">
                                            <?php foreach ($optionsResult as $option): ?>
												<span class="order-product-color"><?php echo  $option['label'] ?>:</span>
												<span class="color-name"><?php echo  $option['value'] ?></span>
                                            <?php endforeach; ?>
										</p>
									</div>
								</div>
								<div class="review-product-rating">
									<div class="ratings big-rating">
										<div class="rating-box">
                                            <?php
                                            $_votes =  Mage::getModel('rating/rating_option_vote')->getCollection()->addFieldToFilter('review_id', $_reviewItem->getReviewId())->load();
                                            ?>
                                            <?php if (count($_votes)): ?>
                                                <?php foreach ($_votes as $_vote): ?>
                                                    <?php if ($_vote->getRatingId() != 4) continue;?>
                                                    <div class="rating" title="Summary"
                                                         style="width:<?= $_vote->getPercent() ?>%"></div>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
										</div>
									</div>
								</div>
								<div class="review-product-status">
									<p class="review-product-words"><?php echo $_reviewItem->getDetail()?></p>
								</div>
							</li>
						<?php endforeach; ?>
					</ul>
					<?php if ($this->getLastPage() > 1): ?>
						<?php
						/* @var Ave40_Widget_Block_Pagination $block */
						$block = Mage::app()->getLayout()->createBlock('ave40_widget/pagination');
						$block->setLastPage($this->getLastPage());
						$block->outputHtml();
						?>
					<?php endif; ?>
				<?php endif; /* not reviewed size is 0 */ ?>
			</div>
		<?php endif; /* reviewed or not reviewed */ ?>
	</div>
</div>

<script>
	~function ($) {
		$(function () {
			$('.main-tab .tab li').off('click');


			$('.not-review-product-status .review-btn').on('click',function () {
				openReviewBox($(this).data('itemId'));
			});

			$('.popup-close').on('click',function () {
				$(this).closest('.popup-box').closeAve40PopupBox();
			});

			$('.star-rating').each(function() {
				var $li = $(this).find("li");

				$li.click(function () {
					$(this).closest('.ratings').find('input.rating').val($(this).data('value'));
					$li.removeClass('on').removeClass('selected');
					var end = $(this).addClass('selected').index();

					for(var i=0; i<=end; i++) {
						$li.eq(i).addClass('on');
					}
				});

				$li.on('mouseover', function () {
					var end = $(this).index();
					$li.removeClass('on')
					for(var i=0; i<=end; i++) {
						$li.eq(i).addClass('on');
					}
				}).on('mouseout', function () {
					var $selectLi = $li.filter('.selected');
					$li.removeClass('on');
					var end = $selectLi.index();

					for(var i=0; i<=end; i++) {
						$li.eq(i).addClass('on');
					}
				});
			});

			$("#review_form").validate({
				errorClass:'mess-error-tip',
				errorElement:"div",

				errorPlacement: function(error, element) {
					error.hide();
				},
				submitHandler:function(form) {

                    // $('#review-upload-input').uploadifive('upload');

					var $this = $(this);
					$('.review-pop').closeAve40PopupBox();
					ave40.showLoading('Reviewing...');

					if($this.getAndInBusying()) {
						return ;
					}
					ave40.ajaxPost('/ave40api/review/item', $('#review_form').serialize(), function () {
						if(this.ok) {
                            Ave40MessageBox.alertSuccess("Thank you for your comment. It has been submitted successfully.");
							location.reload();

						} else {
							Ave40MessageBox.alertError(this.message);
							ave40.closeLoading();
							$('.review-pop').showAve40PopupBox();
						}

						$this.outBusying();
					});
				}
			});

/**
 *  评分图片上传
 */

            var Upload = (function(){
                var upimg = document.getElementById('review-upload-input');
                var show  = document.getElementById('queue');
                var drag = document.getElementById('review-upload-input');

                function init(){
                    if(!(window.FileReader && window.File && window.FileList && window.Blob)){
                        show.innerHTML = 'Your browser does not support it fileReader';
                        upimg.setAttribute('disabled', 'disabled');
                        return false;
                    }
                    if(!upimg){
                        return false;
                    }

                    handler();
                }

                function handler(){
                    upimg.addEventListener('change', function(e){
                        var files = this.files;

                        var show_img = show.getElementsByTagName("img");
                        if(files.length  && show_img.length <=4 ){
                            checkFile(this.files);
                        }else{
                            alert('You are upload up to five')
                        }
                    });

                    drag.addEventListener('dragenter', function(e){
                        this.className = 'drag_hover';
                    }, false);
                    drag.addEventListener('dragleave', function(e){
                        this.className = '';
                    }, false);
                    drag.addEventListener('drop', function(e){
                        var files = e.dataTransfer.files;
                        this.className = '';
                        if (files.length != 0) {
                            checkFile(files);
                        };

                        e.preventDefault();
                    }, false)
                    drag.addEventListener('dragover', function(e){
                        e.dataTransfer.dragEffect = 'copy';
                        e.preventDefault();
                    }, false);

                    show.addEventListener('click', function(e){
                        var target = e.target;
                        if(target.tagName.toUpperCase()=='IMG'){
                            var parent = target.parentNode;
                            var big = parent.className.indexOf('big')>=0;
                            var item = this.childNodes;
                            for(var i=0; i<item.length; i++){
                                item[i].className = 'item';
                                item[i].firstElementChild.style.cssText = '';
                            }

                            var parent = target.parentNode;
                            if(!big){
                                // 点击放大

                                target.style.cssText = 'width:'+target.naturalWidth+'px; height:'+target.naturalHeight+'px;';
                                parent.className += ' big';
                            }
                        }
                    }, false)

                }

                function checkFile(files){
                    if (files.length != 0) {
                        //获取文件并用FileReader进行读取
                        var html = '';
                        var i = 0, j = show.childElementCount;
                        var funcs = function(){
                            if(files[i]){
                                var x = parseInt((i+j)/4)*40;
                                var y = ((i+j)%4)*40;
                                var reader = new FileReader();
                                if(!/image\/\w+/.test(files[i].type)){
                                   alert("Make sure the file is an image type !");
                                    return false;
                                }
                                reader.onload = function(e) {
                                    html += '<div class="item" style="top:'+x+'px; left:'+y+'px;"><img src="'+e.target.result+'" alt=""></div>';
                                    i++;

                                    /*jQuery.post("", { img: e.target.result},function(res){
                                        if(res.img!=''){
                                            alert('upload success');
                                        }else{
                                            alert('upload fail');
                                        }
                                    },'json');*/

                                    funcs();
                                };
                                reader.readAsDataURL(files[i]);
                            }else{
                                show.innerHTML += html;
                            }
                        }
                        funcs();
                    }
                }


                return {
                    init : init
                }
            })();
            Upload.init();






			/*
			$('.submit-btn').submit(function (event) {
				$('.review-pop').closeAve40PopupBox();
				ave40.showLoading('Reviewing');

				if($this.getAndInBusying()) {
					return ;
				}

				ave40.ajaxPost('/ave40api/review/item', $('#review_form').serialize(), function () {
					if(this.ok) {
						ave40.getLoading().setAlertText('Reloading');
						location.reload();
					} else {
						Ave40MessageBox.alertError(this.message);
						ave40.closeLoading();
						$('.review-pop').showAve40PopupBox();
					}

					$this.outBusying();
				});
			});
			*/

			function openReviewBox(itemid) {
				// var item = $('#item_id');
				// var comment = $('#comment_value');
				// var star = $('#star_value');
				//
				// if(!item[0].dataReview) {
				// 	item[0].dataReview = {};
				// }
				//
				// if(item.val() != itemid) {
				// 	item[0].dataReview[item.val()] = {comment:comment.val(), star:star.val()}
				// 	item.val(itemid);
				//
				// 	if(!item[0].dataReview[itemid]) {
				// 		item[0].dataReview[itemid] = {comment:'', star:''}
				// 	}
				//
				// 	comment.val(item[0].dataReview[itemid].comment);
				//
				// 	if(item[0].dataReview[itemid].star) {
				// 		$li.filter('[data-value='+item[0].dataReview[itemid].star+']').click();
				// 	} else {
				// 		$li.removeClass('on').removeClass('selected');
				// 		star.val('');
				// 	}
				// }
				//

				var item = $('#item_id');
				item.val(itemid);

				if(window.reviewItemId != itemid) {
					window.reviewItemId = itemid;
					$('.ratings li').removeClass('selected').removeClass('on');
					$('.ratings').find('input.rating').val('');
					$('#comment_value').val('');
				}

				$('.review-pop').showAve40PopupBox();
			}


			// /*评分功能*/
			// var aLi = $('.star-rating').find("li");
			// var i = iScore = iStar = 0;
			// for (i = 1; i <= aLi.length; i++) {
			// 	aLi[i - 1].index = i;
			// 	aLi[i - 1].onmouseover = function () {
			// 		fnPoint(this.index);
			// 	};
			// 	aLi[i - 1].onmouseout = function () {
			// 		fnPoint();
			// 	};
			// 	aLi[i - 1].onclick = function () {
			// 		iStar = this.index;
			// 	}
			// }
			// function fnPoint(iArg) {
			// 	iScore = iArg || iStar;
			// 	for (i = 0; i < aLi.length; i++) {
			// 		aLi[i].className = i < iScore ? "on" : "";
			// 	}
			// }

		});

	}(jQuery);
</script>
