<?php
/**
 * @see Mage_Paypal_Block_Logo
 */
?>
<div class="paypal-logo">
    <a href="#" title="<?php echo Mage::helper('paypal')->__('Additional Options') ?>" onclick="javascript:window.open('<?php echo $this->getAboutPaypalPageUrl() ?>','paypal','width=600,height=350,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;"><img src="<?php echo $this->getSkinUrl('images/paypal-logo.gif') ?>" alt="<?php echo Mage::helper('paypal')->__('Additional Options') ?>" title="<?php echo Mage::helper('paypal')->__('Additional Options') ?>" /></a>
</div>
