<?php
/**
 * Template for Mage_Page_Block_Html
 */
$__HTMLCache = [];

$__HTMLCache['content'] = $this->getChildHtml('content');
$__HTMLCache['header'] = $this->getChildHtml('header');
$__HTMLCache['head'] = $this->getChildHtml('head');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $__HTMLCache['head'] ?>
</head>
<body <?php echo $this->getBodyClass()?' class="'.$this->getBodyClass(). ' store_' . Mage::app()->getStore()->getCode() . '"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
	<?php echo $this->getChildHtml('global_notices') ?>
	<div class="page" id="all-content">
		<?php echo $__HTMLCache['header'] ?>
		<div class="main-container col1-layout">
			<div class="main">
				<?php echo $this->getChildHtml('breadcrumbs') ?>
				<div class="col-main">
					<?php echo $this->getChildHtml('global_messages') ?>
					<?php echo $__HTMLCache['content'] ?>
				</div>
			</div>
		</div>
		<?php if ($this->getChildHtml('before_footer')): ?>
		<div class="before_footer">
			<?php echo $this->getChildHtml('before_footer') ?>
			<div class="clear"></div>
		</div>
		<?php endif; ?>
		<?php echo $this->getChildHtml('footer') ?>
		<?php echo $this->getChildHtml('before_body_end') ?>
	</div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
