<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body <?php echo $this->getBodyClass()?' class="'.$this->getBodyClass(). ' store_' . Mage::app()->getStore()->getCode() . '"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
	<?php echo $this->getChildHtml('global_notices') ?>
	<div id="all-content" class="page">
		<?php echo $this->getChildHtml('header') ?>
		<div class="main-container col2-left-layout">
			<div class="main">
				<?php echo $this->getChildHtml('breadcrumbs') ?>
				<div class="col-left sidebar" ><?php echo $this->getChildHtml('left') ?></div>
                <div class="col-main ">
                    <?php echo $this->getChildHtml('global_messages') ?>
                    <?php echo $this->getChildHtml('content') ?>
                </div>
			</div>
		</div>
		<?php if ($this->getChildHtml('before_footer')): ?>
		<div class="before_footer">
			<?php echo $this->getChildHtml('before_footer') ?>
			<div class="clear"></div>
		</div>
		<?php endif; ?>
		<?php echo $this->getChildHtml('footer') ?>
		<?php echo $this->getChildHtml('before_body_end') ?>
	</div>

	<script type="text/javascript">
		jQuery(document).ready(function() {
			myHeight= (jQuery('#custommenu').height() + 11) +'px';
			jQuery(".cms-home .col-left").css("marginTop", myHeight);
		});
	</script>

</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
