<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/21
 * Time: 下午 4:57
 */

/* @var Ave40_Catalog_Block_Product_Items $this */
$_productCollection = $this->getProductCollection();

$vars = [
	'only_list' => !!$this->getData('only_list'),
	'special_countdown' => !!$this->getData('special_countdown'),
	'mouse_over_tools' => !!(($this->getData('mouse_over_tools')===null) ? true : $this->getData('mouse_over_tools')),
	'enable_pagination' => $this->getData('enable_pagination'),
	'display_aslowas_price' => !!(($this->getData('display_aslowas_price')==null) ? true : $this->getData('display_aslowas_price')),
];

if($vars['special_countdown']):
	$__isOutOfSpecialDate = function($product) {
		$fromDate = $product->getSpecialFromDate();
		$toDate = $product->getSpecialToDate();
		$now = time();

		return $now < strtotime($fromDate) || $now > strtotime($toDate);
	};

	$__calcDetailTwoDate = function ($start, $end) {
		$start = is_numeric($start) ? $start : strtotime($start);
		$end = is_numeric($end) ? $end : strtotime($end);
		$dvalue = $end - $start;

		$days=0;
		$hours=0;
		$minutes=0;
		$seconds=0;

		if($dvalue > 0) {
			$minSeconds = 60;
			$hourSeconds = 60 * $minSeconds;
			$daySecond = 24 * $hourSeconds;

			$days = floor ($dvalue / $daySecond);
			$dvalue -= $days * $daySecond;
			$hours = floor( $dvalue / $hourSeconds);
			$dvalue -= $hours * $hourSeconds;
			$minutes = floor( $dvalue / $minSeconds);
			$dvalue -= $minutes * $minSeconds;
			$seconds = $dvalue;
		}

		$result = compact(explode(' ', 'days hours minutes seconds'));
		$result['start_time'] = $start;
		$result['end_time'] = $end;
		return $result;
	};

	$__getProductSpecialDateDetail = function ($product) use ($__calcDetailTwoDate) {
		$toDate = $product->getSpecialToDate();
		$now = time();

		return $__calcDetailTwoDate($now, $toDate);
	};
endif; /* special_countdown is enabled */

$imageSize = $this->getImageSize();
$imageWidth = 170;
$imageHeight = 170;

if(!empty($imageSize)) {
	list($_width, $_height) = explode(',', $imageSize);

	if(!(empty($_width) && empty($_height))) {
		$_width = empty($_width) ? $_height : $_width;
		$_height = empty($_height) ? $_width : $_height;
		$imageWidth = intval($_width);
		$imageHeight = intval($_height);
	}
}

$currentTime = time();
$currentDate = date('Y-m-d', $currentTime);

Mage::unregister('current_category');
?>

<?php if (!$vars['only_list']): ?>
<ul class="product-items home-list clearfix">
<?php endif; ?>

<?php foreach ($_productCollection as $_product): ?>
	<li class="item" product_id="<?php echo $_product->getId()?>" product_type="<?php echo $_product->getTypeId() ?>" >

		<div class="home-product-img">
			<a href="<?php echo $_product->getProductUrl() ?>" target="_blank" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
				<img class="lazy" data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imageWidth, $imageHeight) ?>"
					 src="<?php echo $this->getData('only_list') ?
						 		$this->helper('catalog/image')->init($_product, 'small_image')->resize($imageWidth, $imageHeight) :
						 		$this->getSkinUrl('images/loader.gif'); ?>" width="<?php echo $imageWidth ?>" height="<?php echo $imageHeight ?>"
					 alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
			</a>
		</div>
		<div class="product-other-info">
            <div class="flash-countdown">
            <?php if($vars['special_countdown'] && !$__isOutOfSpecialDate($_product)): ?><?php /* 特价结束日期倒计时 */ ?>
                <?php
                $specialDateDetail = $__getProductSpecialDateDetail($_product);
                $countdownId = sha1(uniqid('ctdid', true));
                $countdownSctiptParamDay = "#$countdownId .deal-day";
                $countdownSctiptParamHour = "#$countdownId .deal-hour";
                $countdownSctiptParamMinute = "#$countdownId .deal-minute";
                $countdownSctiptParamSecond = "#$countdownId .deal-second";
                ?>
                <div class="countdown-time"
                     data-cdt-start-time="<?php echo $specialDateDetail['start_time'] ?>"
                     data-cdt-end-time="<?php echo $specialDateDetail['end_time'] ?>">
                    <span class="limit-deal-time">
                        <span class="status-title">Ends In:</span>
                        <span id="<?php echo $countdownId ?>" class="js-limitDealTime">

                            <span class="deal-hour"><?php echo $specialDateDetail['hours'] ?></span>
                             <span><?php echo $this->__('h:') ?></span>
                            <span class="deal-minute"><?php echo $specialDateDetail['minutes'] ?></span>
                             <span><?php echo $this->__('m:') ?></span>
                            <span class="deal-second"><?php echo $specialDateDetail['seconds'] ?></span>
                             <span><?php echo $this->__('s') ?></span>
                        </span>
                    </span>
                </div>
                <script>
                    countDown("<?php echo $_product->getSpecialToDate() ?>",
                        "<?php echo $countdownSctiptParamDay ?>",
                        "<?php echo $countdownSctiptParamHour ?>",
                        "<?php echo $countdownSctiptParamMinute ?>",
                        "<?php echo $countdownSctiptParamSecond ?>"
                    );
                </script>
            <?php endif; ?>
            </div>
			<?php if($vars['mouse_over_tools']): ?>
                <?php Mage::unregister('ave40_instance_product_items_block'); ?>
				<?php Mage::register('ave40_instance_product_items_block', $this); ?>
				<?php echo $this->getReviewsSummaryHtml($_product, 'short', true) ?>
                <?php Mage::unregister('ave40_instance_product_items_block'); ?>
			<?php endif; ?>
			<h2 class="product-name">
				<?php if($_product->getFinalPrice() && $_product->getFinalPrice() < $_product->getPrice()):?>
					<?php $discountPercent =  ceil(round(($_product->getPrice() - $_product->getFinalPrice()) / $_product->getPrice(), 2) * 100) ?>
					<div class="sales-label">
						<i class="sales-off-num"><?php echo $discountPercent ?></i>
					</div>
				<?php endif; ?>
				<a href="<?php echo $_product->getProductUrl() ?>" target="_blank" title="<?php echo $this->htmlEscape($_product->getName()) ?>)"><?php echo $this->htmlEscape($_product->getName()) ?></a>
			</h2>
            <?php
			$proDate = $this->getProDate();
			
            $costTime = $currentTime - strtotime(date('Y-m-d 00:00:00', $currentTime));
            mt_srand($_product->getId());
            $customQty = mt_rand(3500, 32000);
            $commonSpeed = $customQty/(24*3600);
            $lowest = $customQty * mt_rand(2, 60)/100;
            $speed = $commonSpeed * (mt_rand(110, 300) / 100);
            $remQty = $customQty - $costTime * $speed;
            $remQty = $remQty < $lowest ? $lowest : $remQty;
            $remQty = intval($remQty);

            if($proDate < $currentDate) {
                $qtyPercent = ($lowest/$customQty) * 100;
			} else if($proDate > $currentDate) {
                $qtyPercent = 100;
            } else {
                $qtyPercent = intval(($remQty / $customQty ) * 100);
			}
            
            
            $qtyPercent = $qtyPercent <=0 ? 2 : $qtyPercent;
            $qtyPercent = $qtyPercent > 100 ? 100 : $qtyPercent;
            
            
            // ?>
            <div class="number">
                <div class="num_bar"><span style="width: <?php echo $qtyPercent ?>%;"></span></div>
                <div class="ordered_limited clearfix">
                    <span class="ordered"><?php echo $qtyPercent ?>% ordered</span>
                    <!--<span class="limited">Limited --><?php //echo $remQty ?><!--</span>-->
                </div>
            </div>
			
			<?php //强制显示特价, 搭配下面的getPriceHtml
				$_product->setSpecialFromDate('2000-01-01 00:00:00') ;
				$_product->setSpecialToDate('2029-01-01 00:00:00');
			?>
            <?php echo $this->getPriceHtml($_product, $vars['display_aslowas_price'], $this->getPriceSuffix()) ?>
            <span class="black-deal-inquire-btn inquireNow-popup-btn"><i class="black-deal-inquire-icon"></i>Inquire</span>
			<div class="clear"></div>
		</div>
		

        <!-- 去掉tpd -->
        <?php /*if ($_product->getData('tpd')): */?><!--
			<i class="tpd-icon" title="TPD compliance" >TPD compliance</i>
        --><?php /*endif */?>

		<?php if($_product->getFinalPrice() && $_product->getFinalPrice() < $_product->getPrice()):?>
			<?php $discountPercent =  ceil(round(($_product->getPrice() - $_product->getFinalPrice()) / $_product->getPrice(), 2) * 100) ?>
			<div class="sales-label hidden">
				<i class="sales-off-num"><?php echo $discountPercent ?></i>
			</div>
		<?php endif; ?>

	</li>
<?php endforeach; ?>


<?php if (!$vars['only_list']): ?>
</ul>
<?php endif; ?>

<?php if($vars['enable_pagination']): ?>
	<?php
		/* @var Ave40_Widget_Block_Pagination	$block */
		$block = Mage::app()->getLayout()->createBlock('ave40_widget/pagination');
		$urlPageKey = $this->getPaginationUrlKey() ? $this->getPaginationUrlKey() : 'page';
		$block->setUrlQueryKey($urlPageKey);
		$block->setCurrentPage($_GET[$urlPageKey] <= 0 ? 1 : $_GET[$urlPageKey]);
		$block->setLastPage($_productCollection->getLastPageNumber());
		$block->outputHtml();
	?>
<?php endif; ?>



