<!--个人中心无内容通用模块-->
<div class="no-content-clusters">
	<!--<img src="<?/*= $this->getSkinUrl('images/personal/person-enpty-02.png') */?>" class="no-con-anim-02" alt="">-->
	<!--<img src="<?/*= $this->getSkinUrl('images/personal/person-enpty-03.png') */?>" class="no-con-anim-03" alt="">
	<img src="<?/*= $this->getSkinUrl('images/personal/person-enpty-04.png') */?>" class="no-con-anim-04" alt="">
	<img src="<?/*= $this->getSkinUrl('images/personal/person-enpty-05.png') */?>" class="no-con-anim-05" alt="">
	<img src="<?/*= $this->getSkinUrl('images/personal/person-enpty-06.png') */?>" class="no-con-anim-06" alt="">-->
</div>