<style>.main {width:100%}  .main .col-main {width:100%; margin:0;}</style>

<script>ave40.params.control.disableTopFloatMenuBar = true;</script>
<div class="forget-password-page">
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <div class="retrieve">
		<div class="retrieve-process clearfix">
			<div class="retrieve-title"><?php echo Mage::helper("Ave40_Translate")->__('Retrieve password:') ?></div>
			<div class="retri-schedule">
				<div class="retri-step-verifi retri-status active">
					<i class="retri-step-ico icon">1</i>
					<p class="retri-step-word">Verification</p>
				</div>
				<div class="line-1 line"></div>
				<div class="retri-step-reset retri-status">
					<i class="retri-step-ico icon">2</i>
					<p class="retri-step-word">Reset password</p>
				</div>
				<div class="line-2 line"></div>
				<div class="retri-step-finish retri-status">
					<i class="retri-step-ico icon">3</i>
					<p class="retri-step-word">Finish</p>
				</div>
			</div>
		</div>

        <div class="email-verify input_form">
			<div class="email-verify-title">
				<i class="tip-icon icon"></i>
				<span class="email-verify-tip">Please complete the following operation to retrieve the password:</span>
			</div>
            <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
                <div class="email-box">
					<label >Email:</label>
                    <input type="email" class="email" name="email" placeholder="Email" required="required"
                           value="<?= $this->getRequest()->getPost('email')?>">
					<span class="forgot-input-tip">Please fill in the correct mailbox</span>
				</div>


                <!--
                <div class="code-box">
					<label >Captcha:</label>
                    <?php /*echo $this->getChildHtml('captcha'); */?>
                </div>
                -->
                <button type="submit" class="email-verify-btn"><?php echo Mage::helper("Ave40_Translate")->__('Email Verify') ?></button>
            </form>
        </div>
    </div>
</div>
<div class="cart-footer">
    <?= $this->getLayout()->getBlock('simple_footer')->toHtml() ?>
</div>
<script type="text/javascript">
	~function ($) {
		$(function () {
			$("#form-validate").validate({
				rules: {
					email: {
						required: true,
						email: true
					}
				},
				errorClass: 'mess-error-tip-dashed',
				errorElement: "div",
				onfocusout:false,
				errorPlacement: function (error, element) {
					error.hide()
				}
			});
		})
	}(jQuery)
</script>