<style>.main {width:100%}  .main .col-main {width:100%; margin:0;}</style>

<script>ave40.params.control.disableTopFloatMenuBar = true;</script>
<div class="forget-password-page">
	<?php echo $this->getMessagesBlock()->toHtml() ?>
	<div class="retrieve">
		<div class="retrieve-process clearfix">
			<div class="retrieve-title"><?php echo Mage::helper("Ave40_Translate")->__('Retrieve password:') ?></div>
			<div class="retri-schedule">
				<div class="retri-step-verifi retri-status active">
					<i class="retri-step-ico icon">1</i>
					<p class="retri-step-word">Verification</p>
				</div>
				<div class="line-1 line active"></div>
				<div class="retri-step-reset retri-status active">
					<i class="retri-step-ico icon">2</i>
					<p class="retri-step-word">Reset password</p>
				</div>
				<div class="line-2 line active"></div>
				<div class="retri-step-finish retri-status active">
					<i class="retri-step-ico icon">3</i>
					<p class="retri-step-word">Finish</p>
				</div>
			</div>
		</div>

		<div class="finish-info">
			<div class="finish-tip">
				<i class="icon finish-icon"></i>
				<span>Password reset successful , please do not forget the new password</span>
			</div>
			<a href="/customer/account/login" class="login-again-btn no-hover">Login again</a>
		</div>
	</div>
</div>