<style>.main {width:100%}  .main .col-main {width:100%; margin:0;}</style>

<script>ave40.params.control.disableTopFloatMenuBar = true;</script>
<div class="forget-password-page">
	<?php echo $this->getMessagesBlock()->toHtml() ?>
	<div class="retrieve">
		<div class="retrieve-process clearfix">
			<div class="retrieve-title"><?php echo Mage::helper("Ave40_Translate")->__('Retrieve password:') ?></div>
			<div class="retri-schedule">
				<div class="retri-step-verifi retri-status active">
					<i class="retri-step-ico icon">1</i>
					<p class="retri-step-word">Verification</p>
				</div>
				<div class="line-1 line active"></div>
				<div class="retri-step-reset retri-status active">
					<i class="retri-step-ico icon">2</i>
					<p class="retri-step-word">Reset password</p>
				</div>
				<div class="line-2 line"></div>
				<div class="retri-step-finish retri-status">
					<i class="retri-step-ico icon">3</i>
					<p class="retri-step-word">Finish</p>
				</div>
			</div>
		</div>

		<div class="reset-passwd input_form">
			<form action="">
				<div class="new-password">
					<label for="">New password:</label>
					<input type="password" required="required">
					<span class="forgot-input-tip">At least six digit password</span>
				</div>
				<div class="cofirm-passwd">
					<label for="">Confirm password:</label>
					<input type="password" required="required">
				</div>
				<button type="submit" class="reset-new-passwd-btn">Submit</button>
			</form>
		</div>
	</div>
</div>
<div class="cart-footer">
	<?= $this->getLayout()->getBlock('simple_footer')->toHtml() ?>
</div>