<?php $_items = $this->getReviewsCollection()->getItems();?>
<div class="box-collateral box-reviews" id="customer-reviews">
    <span class="review-title-top"><?php echo Mage::helper("Ave40_Translate")->__('Product Reviews') ?></span>
	<div class="review-all">
    <?php if (count($_items)):?>
	   <div class="review-item-list">
        <h2 class="title"><?php echo Mage::helper("Ave40_Translate")->__('Customer Reviews') ?></h2>
		<?php if( $this->getReviewsSummaryHtml($this->getProductData())): ?>
		  <div class="average-customer-rating">
             <div class="label"><?php echo Mage::helper("Ave40_Translate")->__('Average Customer Rating') ?>:</div>
             <?php echo $this->getReviewsSummaryHtml($this->getProductData()) ?>
		   </div>
        <?php endif; ?>

        <?php echo $this->getChildHtml('toolbar') ?>
        <dl>
        <?php foreach ($_items as $_review):?>
            <dt>
                <?php echo $this->htmlEscape($_review->getTitle()) ?> <?php echo Mage::helper("Ave40_Translate")->__('Review by <span>%s</span>', $this->htmlEscape($_review->getNickname())) ?>
            </dt>
            <dd>
                <?php $_votes = $_review->getRatingVotes(); ?>
                <?php if (count($_votes)): ?>
                <table class="ratings-table">
                    <col width="1" />
                    <col />
                    <tbody>
                        <?php foreach ($_votes as $_vote): ?>
                        <tr>
                            <th><?php echo $this->escapeHtml($_vote->getRatingCode()) ?></th>
                            <td>
                                <div class="rating-box">
                                    <div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php endif; ?>
                <?php echo nl2br($this->htmlEscape($_review->getDetail())) ?>
                <small class="date"><?php echo Mage::helper("Ave40_Translate")->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt()), 'long') ?></small>
            </dd>
        <?php endforeach; ?>
        </dl>
        <?php echo $this->getChildHtml('toolbar') ?>
	  </div>
    <?php endif;?>
    <?php echo $this->getChildHtml('review_form') ?>
	</div>
</div>
