
<?php $_product = $this->getProduct() ?>

<?php if ($_product->isSaleable()): ?>
	<script type="text/javascript">
		//<![CDATA[
		var skipTierPricePercentUpdate = true;
		var bundle = new Product.Bundle(<?php echo $this->getJsonConfig() ?>);
		var taxCalcMethod = "<?php echo Mage::helper('tax')->getConfig()->getAlgorithm($_product->getStore()) ?>";
		var CACL_UNIT_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_UNIT_BASE ?>";
		var CACL_ROW_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_ROW_BASE ?>";
		var CACL_TOTAL_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_TOTAL_BASE ?>";
		//]]>
	</script>
<?php endif; ?>

<?php if ($this->displayProductStockStatus()): ?>
<div class="qty">
	<span class="words"><?php echo Mage::helper("Ave40_Translate")->__('Availability:') ?></span>
	<?php if ($_product->isAvailable()): ?>
	<span class="status inStock"><?php echo Mage::helper("Ave40_Translate")->__('In stock') ?></span>
	<?php else: ?>
	<span class="status outStock"><?php echo Mage::helper("Ave40_Translate")->__('Out of stock') ?></span>
	<?php endif; ?>
</div>
<?php endif; ?>

<!--
<div class="price-box-bundle">
	<?php echo $this->getPriceHtml($_product) ?>
</div>
<?php echo $this->getChildHtml('bundle_prices') ?>
-->