<?php if($crumbs && is_array($crumbs)): ?>
	<div class="breadcrumbs">
		<ul>
            <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
				<li class="<?php echo $_crumbName ?>">
                    <?php if($_crumbInfo['link']): ?>
						<a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->escapeHtml($_crumbInfo['title']) ?>"><?php echo $this->escapeHtml($_crumbInfo['label']) ?></a>
                    <?php elseif($_crumbInfo['last']): ?>
						<span><?php echo $_crumbInfo['label'] ?></span>
                    <?php else: ?>
                        <?php echo $_crumbInfo['label'] ?>
                    <?php endif; ?>
                    <?php if(!$_crumbInfo['last']): ?>
						<span>/ </span>
                    <?php endif; ?>
				</li>
            <?php endforeach; ?>
		</ul>
	</div>
<?php endif; ?>
