<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<style>
	.fixed {position: fixed;top:0;left:0;width: 100%;background:#fff; z-index:999;-webkit-box-shadow: rgba(0,0,0,.1) 0 1px 5px;-moz-box-shadow: rgba(0,0,0,.1) 0 1px 5px;box-shadow: rgba(0,0,0,.1) 0 1px 5px;padding:0;}
	.fixed .header-container{width:1200px;margin:0 auto;}
	.fixed #topnav,.fixed .home-link,.fixed .currency-switch.language-switch,.fixed .livechat,.fixed .top-myaccount,.fixed .quick-access-right{ display:none !important;}
	.fixed .hidden_menu,.fixed .show_menu{ position:absolute;top:18px;z-index:999;}
	.fixed .quick-access{width:500px;background:#fff;border:none;overflow: hidden;}
	.fixed .block-login{ position:absolute;display:block;right:10px;top:20px;}
	.fixed .block-login .top-links{ border:1px solid #fff;}
	.fixed .block-login .top-links:hover{ border:1px solid #f1f1f1}
	.fixed .topbar{background: #fff;height: 1px;overflow: hidden;}
	.cms-index-index .fixed #custommenu{display:none;}
	.cms-index-index .fixed .show_menu .nav-hover#custommenu{display:block !important;}
	.searchautocomplete .nav .nav-input input{padding-left:15px;}
	.sticky-container{position:relative;margin: 0 auto;}
	.header .quick-access-left{position:relative;}
	.searchautocomplete .searchautocomplete-placeholder{left:48px !important;}
</style>

<script language="javascript">

	jQuery(window).scroll(function() {
		var sticky = jQuery('.sticky');

		if(ave40.params.control.disableTopFloatMenuBar) {
			if(sticky.hasClass('fixed')) {
				sticky.removeClass('fixed');
			}

			return ;
		}

		var scrollTop = jQuery(window).scrollTop();
		var $headerPlaceholder = jQuery('#header-placeholder-elm');

		var borderScrollerTop = $headerPlaceholder.prop('ave40BorderScrollerTop');

		if(!sticky.hasClass('fixed')) {
			if(sticky.find('.nav-container').css('display') != 'none' && sticky.find('.nav-container').outerHeight() > 0) {
				borderScrollerTop = sticky.find('.nav-container').offset().top;
			} else {
				borderScrollerTop = sticky.find('.login_content').offset().top + sticky.find('.login_content').outerHeight()/2;
			}

			$headerPlaceholder.prop('ave40BorderScrollerTop', borderScrollerTop);
		}

		if (scrollTop > borderScrollerTop) {
			if(!sticky.hasClass('fixed')) {
				var oriHeight = sticky.outerHeight();
				$headerPlaceholder.css('paddingTop', (oriHeight) + 'px');
				sticky.addClass('fixed').css('opacity', 1);//.stop().animate({opacity:1}, 500);
			}
		} else {
			if(sticky.hasClass('fixed')) {
				sticky.removeClass('fixed').css('opacity', 1);//.stop().animate({opacity:1}, 300);
				$headerPlaceholder.css('paddingTop', '0px');
			}
		}
	});
</script>

<?php if(!$_COOKIE['top_ad_click']): ?>
	<?=Mage::getModel('core/email_template_filter')->filter(Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('top_ad')->getContent())?>
	<script>
		/* 广告关闭 */
		~function($) {
			$(function () {
				var $topAdClose = $('.top_ad .top-close');

				$topAdClose.off('click');
				$topAdClose.click(function () {
					function setCookie(name,value)
					{
						var Days = 1;
						var exp = new Date();
						exp.setTime(exp.getTime() + Days*24*60*60*1000);
						document.cookie = name + "="+ escape (value) + ";expires=" + exp.toGMTString() + ";path=/";
					}

					setCookie('top_ad_click', 1);
					var $parent = $(this).parent().css('height', $(this).offsetHeight);
					$parent.find('img').animate({height:0}, 500);

					$parent.animate({opacity:0.0, height:0}, 500, null, function () {
						$(this).remove();
					});
				});
			});
		} (jQuery);
	</script>
<?php endif; ?>


<div class="sticky">
	<div class="sticky-container">
		<div class="header-container">
			<div class="header">
				<div class="topbar">
					<div class="topbar_content">
						<div class="home-link">
							<a href="mailto:<?=Mage::getModel('core/variable')->loadByCode('head_contact_email')->getValue('html')?>"><?=Mage::getModel('core/variable')->loadByCode('head_contact_email')->getValue('html')?></a>
						</div>
						<div class="header_right">
							<ul>
								<!--
								<li>
									<a href="?follow_us" title="" class="follow">Follow us</a>
								</li>
								<span class="line"></span>
								-->
								<li class="heder_help">
									<div>
										Help
										<i class="arrow"></i>
										<div class="helpBox">
											<ul>
												<li><a href="/about-us.html">About AVE40</a></li>
												<li><a href="http://archive.ave40.com/">Old site</a></li>

											</ul>
										</div>
									</div>
								</li>
								<span class="line"></span>
								<li><div>Languages</div></li>
								<!--
								<?php echo $this->getChildHtml('store_language'); ?>
								-->
							</ul>
						</div>
					</div>
				</div>

				<div class="login_content">
					<h1 class="logo">
						<strong><?php echo $this->getLogoAlt() ?></strong>
						<a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
							<img src="<?=$this->getSkinUrl('images/media/logo.png')?>" alt="<?php echo $this->getLogoAlt() ?>" />
						</a>
						<i class="light"></i>
					</h1>

					<div class="quick-access">
						<div class="quick-access-left">
							<?php echo $this->getChildHtml('topSearch') ?>
							<?php echo $this->getChildHtml('searchTerm') ?>
						</div>
						<div class="quick-access-right">
							<div class="inquire-service simple-inquire">
								<a href="javascript:;" title="inquire now" class="simple-inquire-icon"></a>
							</div>
							<?php echo $this->getChildHtml('top_cart') ?>
							<?php echo $this->getChildHtml('member') ?>
							<!--
							<?php echo $this->getChildHtml('mini_login') ?>
							-->
						</div>
					</div>

					<div class="clear"></div>
					<?php echo $this->getChildHtml('topContainer'); ?>
				</div>
			</div>
		</div>

		<?php
		$routeName = Mage::app()->getRequest()->getRouteName();
		$identifier = Mage::getSingleton('cms/page')->getIdentifier();
		?>
		<?php if ($this->getIsHomePage() || ($routeName == 'cms' && $identifier == 'home') ):?>
			<div class="show-menu-content">
				<div class="show_menu"><?php echo $this->getChildHtml('topMenu') ?></div>
			</div>
		<?php else: ?>
			<div class="show-menu-content">
				<div class="hidden_menu"><?php echo $this->getChildHtml('topMenu') ?></div>
			</div>
		<?php endif; ?>
	</div>
</div>
<div id="header-placeholder-elm" style="width:0; height:0; magin:0;"></div>
<?php
echo Mage::app()->getLayout()->createBlock('core/template')->setTemplate('inquire/simple-form.phtml')->toHtml();
?>
<?php if (!$_COOKIE['18_jin_tip'] && !Mage::getStoreConfig('ave40_developer/show18notice/disabled') ): ?>
	<?php //if (true): ?>
	<div class="ave-18notice">
		<?php ob_start(); ob_flush(); ?>
		<div class="ani-body">
			<div class="ave40notice-tip">
				<img src="<?=$this->getSkinUrl('images/homepage/ave18-tip.png')?>" alt="">
				<p><?php echo Mage::helper("Ave40_Translate")->__('The products on this website are intended for ADULTS only.') ?></p>
				<p><?php echo Mage::helper("Ave40_Translate")->__('Please leave this page!') ?></p>
				<span class="ave40-tip-close"><?php echo Mage::helper("Ave40_Translate")->__('CLOSE') ?></span>
			</div>

			<div class="ave-18notice-body">
				<span class="ave18notice-btn ave-18notice-true"><?php echo Mage::helper("Ave40_Translate")->__('Yes') ?></span>
				<span class="ave18notice-btn ave-18notice-flase"><?php echo Mage::helper("Ave40_Translate")->__('No') ?></span>
				<img src="<?=$this->getSkinUrl('images/homepage/18notice-01.png')?>" alt="">
			</div>

			<div class="ave-18notice-footer">
				<img src="<?=$this->getSkinUrl('images/homepage/18notice-02.png')?>" alt="">
			</div>
		</div>
		<?php $obhtml = htmlspecialchars(ob_get_contents()); ob_end_clean(); echo $obhtml; ?>

	</div>
	<script>
		~function($) {
			$(function () {
				var $ave18notice = $('.ave-18notice');
				if($ave18notice.find('.ave-18notice-body').length > 0) {
					$ave18notice.letHVCenter().showAve40PopupBox();
				} else {
					$ave18notice.html(ave40.unescapeHtml($ave18notice.html()))
						.letHVCenter().showAve40PopupBox();
				}

				$('.ave-18notice-true').click(function(){
					var $notice = $('.ave-18notice');
					var $simpleInquire = $('.simple-inquire');
					setCookie('18_jin_tip', 1);

					if($simpleInquire.length <= 0) {
						$notice.closeAve40PopupBox();
						return;
					}

					var scrollTop = $(document).scrollTop();
					var scrollLeft = $(document).scrollLeft();
					var $footer = $notice.find('.ave-18notice-footer');
					var pbLeft = $notice.offset().left - scrollLeft;
					var pbTop = $notice.offset().top - scrollTop;
					var siLeft = $simpleInquire.offset().left - scrollLeft;
					var siTop = $simpleInquire.offset().top - scrollTop;

					var pbWidth = $notice.outerWidth();
					var pbHeight = $notice.outerHeight();
					var siWidth = $simpleInquire.outerWidth();
					var siHeight = $simpleInquire.outerHeight();

					var pbCenterTop = pbTop + pbHeight/2;
					var pbCenterLeft = pbLeft + pbWidth/2;
					var siCenterLeft = siLeft + siWidth/2;
					var siCenterTop = siTop + siHeight/2;

					var targetRotateX = 20;
					var targetRotateY = 20;
					var targetRotateZ = 20;

					$notice.css({margin:0, left:pbLeft, top:pbTop});
					var name = 'animateUnit' + String(Math.random()).substr(2);
					var data = {};
					data[name] = 1000;

					$footer.animate({opacity: 0}, 1000);

					$notice.stop().animate(data, {
						step: function (now) {
							var percent = now/1000;
							var scale = 1.05 - percent;
							scale = scale > 1 ? 1 : scale;
							var opacity = 1.5 - percent;
							var left = pbLeft + (siCenterLeft-pbCenterLeft)*percent;
							var top = pbTop + (siCenterTop-pbCenterTop)*percent;

							var rx = targetRotateX * percent;
							var ry = targetRotateY * percent;
							var rz = targetRotateZ * percent;

							jQuery(this).css('opacity', opacity);
							jQuery(this).css({left:left, top:top});
							jQuery(this).css('transform', 'perspective(200px) scale('+scale+') ' +
								'rotateX('+ rx +'deg) rotateY('+ ry +'deg) rotate('+ rz +'deg)');
						},
						duration: 1200,
						complete: function () {
							spotlightInquireIcon(1);
							$(this).animate({opacity:0}, 300, function () {
								$(this).hide();
								ave40.getOverlay().hideOverlay();
							});
						},

						easing:'swing'
					});

					function spotlightInquireIcon(n)
					{
						n = n == undefined ? 1 : n;

						if(n == 1) {
							makeIcon(1);
							return;
						}

						for(var i=0; i<n; i++) {
							setTimeout(function() {
								makeIcon(i);
							}, i*50);
						}

						function makeIcon(z)
						{
							var $simpleInquire = $('.simple-inquire');
							var $icon = $simpleInquire.find('a');
							var html = $icon[0].outerHTML;

							var $nico = $(html);
							$simpleInquire.append($nico);
							$nico.css({position:'absolute', top:0, left:0, zIndex:1000-z}).animate({
								anmateUnit:1000
							}, {
								step: function (now) {
									var percent = now/1000;
									var scale = tofixed(1+0.5*percent, 2);
									var opacity = 1 - percent;

									jQuery(this).css({'opacity': opacity, 'transform': 'scale('+scale+')'});
								},
								duration: 600,
								complete: function () {
									$(this).remove();
								}
							});
						}
					}

					function tofixed(num, length)
					{
						if(Number(num).toFixed) {
							return Number(num).toFixed(length);
						} else {
							return num;
						}
					}

					function setCookie(name,value)
					{
						var Days = 30;
						var exp = new Date();
						exp.setTime(exp.getTime() + Days*24*60*60*1000);
						document.cookie = name + "="+ escape (value) + ";expires=" + exp.toGMTString() + ";path=/";
					}
				});

				$('.ave-18notice-flase').click(function(){
					$('.ave40notice-tip').show();
					$('.ave-18notice-body').hide();
					$('.ave-18notice-footer').hide();
					$('.ave-18notice').letHVCenter();
				});

				$('.ave40-tip-close').click(function () {
					$('.ave-18notice').closeAve40PopupBox();
				});
			});
		} (jQuery);
	</script>
<?php endif; ?>

<script type="text/javascript">
	~function($){
		$(function () {
			$('.simple-inquire').click(function () {
				$('#simple-inquireNow-info').showAve40PopupBox();
			});
		})
	}(jQuery)

</script>
