<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<?php if (!$_COOKIE['top_ad_click']): ?>
    <?= Mage::getModel('core/email_template_filter')->filter(Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load('top_ad')->getContent()) ?>

<?php endif; ?>
<?= $this->getChildHtml('jstranslate') ?>
<div class="sticky">

    <div class="sticky-container">
        <div class="header-container">
            <div class="header">
                <div class="topbar">
                    <div class="topbar_content">
                        <div class="home-link">
                            Free Shipping on Orders over $50 !
                        </div>
                        <div class="header_right">
                            <ul>
                                <li><a href="/blog/" title="ave40_blog" target="_blank"><?= Mage::helper("Ave40_Translate")->__('Blog')?></a></li>
                                <li class="sign-in-column">
                                    <i class="sign-in-icon"></i>

                                    <?php if (!Mage::getModel('customer/session')->isLoggedIn()): ?>
                                        <a href="/customer/account/login" title="<?= Mage::helper("Ave40_Translate")->__('Sign In')?>" rel="nofollow"  class="sign-in-link"
                                           onclick="_gaq.push(['_trackEvent','SignIn_header_outSide_button','Click','SignIn_header_outSide_button']);">
                                            <?= Mage::helper("Ave40_Translate")->__('Sign In')?>
                                        </a>
                                    <?php else: ?>
                                        <a href="/customer/account/" title="<?= Mage::helper("Ave40_Translate")->__('Sign In')?>" rel="nofollow" class="sign-in-link">
                                            <?php echo Mage::getModel('customer/session')->getCustomer()->getName() ?>
                                        </a>
                                    <?php endif; ?>

                                    <?php if (!Mage::getModel('customer/session')->isLoggedIn()): ?>
                                        <div class="login_pop">
                                            <div class="sign_in">
                                                <span> <?= Mage::helper("Ave40_Translate")->__('Welcome to')?> <i class="ave-words">AVE40.com</i></span>
                                                <a href="/customer/account/login" onclick="_gaq.push(['_trackEvent','SignIn_header_inSide_button','Click','SignIn_header_inSide_button']);">
                                                    <span class="sign_btn loginBtn"><?= Mage::helper("Ave40_Translate")->__('Sign In')?></span>
                                                </a>
                                                <?php if (Mage::getStoreConfig('ave40_login/global/enabled')): ?>
                                                    <div class="sign_way">
                                                        <span><?= Mage::helper("Ave40_Translate")->__('Sign In with')?></span>

                                                        <?php if (Mage::getStoreConfig('ave40_login/facebook/enabled')): ?>
                                                            <a href="/login?platform=facebook&action=do_login"
                                                               title="Facebook" class="icon facebook-icon"></a>
                                                        <?php endif ?>

                                                        <?php if (Mage::getStoreConfig('ave40_login/instagram/enabled')): ?>
                                                            <a href="/login?platform=instagram&action=do_login"
                                                               title="Instagram" class="icon ins-icon"></a>
                                                        <?php endif ?>

                                                        <?php if (Mage::getStoreConfig('ave40_login/google/enabled')): ?>
                                                            <a href="/login?platform=google&action=do_login"
                                                               title="Google" class="icon google-icon"></a>
                                                        <?php endif ?>

                                                        <?php if (Mage::getStoreConfig('ave40_login/vk/enabled')): ?>
                                                            <a href="/login?platform=vk&action=do_login" title="VK"
                                                               class="icon vk-icon"></a>
                                                        <?php endif ?>

                                                        <?php if (Mage::getStoreConfig('ave40_login/twitter/enabled')): ?>
                                                            <a href="/login?platform=twitter&action=do_login"
                                                               title="Twitter" class="icon twitter-icon"></a>
                                                        <?php endif ?>

                                                    </div>
                                                <?php endif ?>
                                            </div>
                                            <div class="join_free">
                                                <span class="newAver"><?= Mage::helper("Ave40_Translate")->__('New Customer?')?></span>
                                                <a href="/customer/account/create" onclick="_gaq.push(['_trackEvent','JoinFree_header_button','Click','JoinFree_header_button']);"><span class="join_btn loginBtn"><?= Mage::helper("Ave40_Translate")->__('Join Free')?></span></a>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </li>

                                <?php if (Mage::getModel('customer/session')->isLoggedIn()): ?>
                                    <li class="my-account">
                                        <a href="/customer/account/" title="myaccount" class="myaccount-link"><?= Mage::helper("Ave40_Translate")->__('My Account')?></a>
                                        <i class="topbar-arrow-icon"></i>
                                        <div class="login_pop logined-login-pop">
                                            <div class="information">
                                                <ul>
                                                    <li><a href="/wishlist"><?= Mage::helper("Ave40_Translate")->__('My Wishlist')?></a></li>
                                                    <li><a href="/sales/order/history"><?= Mage::helper("Ave40_Translate")->__('My Orders')?></a></li>
                                                    <li><a href="/customer/account/logout" class="signIn"><?= Mage::helper("Ave40_Translate")->__('Logout')?></a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                <?php endif; ?>

                                <li class="heder_help">
                                    <div>
                                        <span><?= Mage::helper("Ave40_Translate")->__('Help')?></span>
                                        <i class="topbar-arrow-icon"></i>
                                        <div class="helpBox">
                                            <ul>
                                                <li><a rel="nofollow" href="/new-user-guide.html"><?= Mage::helper("Ave40_Translate")->__('New User Guide')?></a>
                                                </li>
                                                <li><a rel="nofollow" href="/about-us.html"><?= Mage::helper("Ave40_Translate")->__('About AVE40')?></a></li>
                                                <li><a rel="nofollow" href="http://archive.ave40.com/"><?= Mage::helper("Ave40_Translate")->__('Old site')?></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </li>
                                
                                <li class="languages-list">
                                    <div>
                                        <span>Languages</span>
                                        <i class="topbar-arrow-icon"></i>

                                        <div class="languagesBox" >
                                            <ul>
                                                <li>Other Languages are coming soon !</li>
                                            </ul>
                                        </div>
                                    </div>
                                </li>
                                
						        <?php //echo $this->getChildHtml('store_language'); ?>
								
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="login_content">
                    <i class="i_menu"></i>
                    <h5 class="logo">
                        <strong><?php echo $this->getLogoAlt() ?></strong>
                        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"
                           class="logo"
                           style="background: url('/skin/frontend/default/se105/images/media/logo.png') no-repeat center">
                        </a>
                    </h5>
                    <div class="quick-access">
                        <div class="quick-access-left">

                            <?php echo $this->getChildHtml('topSearch') ?>
                            <?php echo $this->getChildHtml('searchTerm') ?>

                            <!--<div class="inquire-service simple-inquire inquireNow-popup-btn">
                                <a href="javascript:;" title="inquire now" class="simple-inquire-icon"></a>-->

                                <!-- 询盘按钮提示 -->
                              <!--  <?php /*if (!$_COOKIE['simple-inquire-tip']): */?>
                                    <a href="javascript:;" class="simple-inquire-tip-close">
                                        <img class="simple-inquire-tip"
                                             src="<?/*= $this->getSkinUrl('images/homepage/simple-pop-tip.png') */?>"
                                             alt=""/>
                                    </a>

                                    <script type="text/javascript">
                                        ~function ($) {
                                            $(function () {
                                                var $quick_inquire = $('.quick-access-left .simple-inquire');
                                                var $inquire_tip_close = $('.simple-inquire-tip-close');


                                                $(window).resize(function () {
                                                    ave40.getOverlay(jQuery('.simple-inquire')).css({
                                                        position: 'fixed',
                                                        left: 0,
                                                        zIndex: 10010,
                                                        top: 0,
                                                        width: jQuery('body').innerWidth(),
                                                        height: jQuery('body').innerHeight(),
                                                    });
                                                });

                                                ave40.getOverlay(jQuery('.simple-inquire')).showOverlay();

                                                ave40.getOverlay(jQuery('.simple-inquire')).css({
                                                    position: 'fixed',
                                                    left: 0,
                                                    zIndex: 10010,
                                                    top: 0,
                                                    width: jQuery('body').innerWidth(),
                                                    height: jQuery('body').innerHeight(),
                                                });

                                                $('.sticky').css({zIndex: 10009});

                                                $('.simple-inquire-icon').css({position: 'relative', zIndex: 10016});

                                                $inquire_tip_close.css({zIndex: 10015});

                                                $('.simple-inquire-tip').animateShow();

                                                $inquire_tip_close.click(function () {
                                                    ave40.setCookie('simple-inquire-tip', 1)
                                                    $('.simple-inquire-tip').animateHide();
                                                    ave40.getOverlay(jQuery('.simple-inquire')).hideOverlay();
                                                    $('.sticky').css({zIndex: ''});
                                                    $('.simple-inquire-icon').css({zIndex: ''});
                                                    return false;
                                                });
                                            })
                                        }(jQuery)


                                    </script>
                                --><?php /*endif; */?>

                            <!--</div>-->


                        </div>

                        <?php echo $this->getChildHtml('top_cart') ?>

                    </div>

                    <div class="clear"></div>
                    <?php echo $this->getChildHtml('topContainer'); ?>
                </div>

				<?php if(avepcache_begin('global_nav')): ?>
                <div class="nav-column clearfix">
                    <div id="topnav">

                        <div class="category_wrap">
                            <div class="cate_title">Categories</div>
                            <ul>
                                <li>
                                    <a href="/All-Brands.html" class="prime"><i class="icon-1"></i>Brands</a>
                                </li>
                                <li>
                                    <a href="/All-Brands.html" class="prime"><i class="icon-1"></i>Brands</a>
                                </li>
                                <li>
                                    <a href="/All-Brands.html" class="prime"><i class="icon-1"></i>Brands</a>
                                </li>
                                <li>
                                    <a href="/All-Brands.html" class="prime"><i class="icon-1"></i>Brands</a>
                                </li>
                            </ul>
                        </div>

                        <ul>
                            <li class="top-link1">
                                <a href="/brands"><span><?= Mage::helper("Ave40_Translate")->__('BRANDS')?></span></a>
                                <div class="topnav-poplayer brands">
                                    <div class="topnav-poplayer-main" style="padding: 10px 10px 10px 0px">
                                        <ul class="topnav-main-product-list">
                                            <?php foreach (Mage::helper('ave40_brands')->getBrands()['brands_data'] as $brand): ?>
                                                <?php
                                                $urlkey = $brand->getUrlKey();
                                                $urlPath = $brand->getUrlPath();
                                                $className = '';

                                                if(in_array($urlkey, ['smoant','vaporesso','ijoy'])) {
                                                    $urlPath = $urlPath . '-sale';
                                                    $className = 'hot';
                                                }
                                                ?>
                                                <li class="topnav-main-product-li <?php echo $urlkey . ' ' . $className ?> ">
                                                    <div class="topnav-main-title"><a style="font-weight:normal;"
                                                                                      href="/<?php echo ltrim($urlPath, '/') ?>"><?= Mage::helper("Ave40_Translate")->__($brand->getName())?></a>
                                                    </div>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </div>
                            </li>

                            <?php echo Mage::app()->getLayout()->createBlock('cms/block')->setBlockId('new-navigation-front')->toHtml() ?>

                            <?php //$categoryId = Mage::helper('ave40_api')->getCustomConfigValue('category_id/navigation'); ?>
                            <?php //$category = Mage::getModel('catalog/category')->load($categoryId) ?>
                            <?php //if($category->getId()): ?>
                            <?php foreach (Mage::helper('catalog/category')->getStoreCategories() as $categoryItem): ?>
                                <?php $categoryItem = Mage::getModel('catalog/category')->load($categoryItem->getId()) ?>
                                <li class="top-link2 nav-<?php echo trim($categoryItem->getUrlPath(), '/') ?>"
                                    data-fill-parent="yes">
                                    <a href="<?php echo '/' . ltrim($categoryItem->getUrlPath(), '/') ?>"><span><?= Mage::helper("Ave40_Translate")->__($categoryItem->getName())?></span></a>
                                    <div class="topnav-poplayer starterkits">
                                        <div class="topnav-poplayer-head">
                                            <ul data-fill-id="<?php echo ltrim($categoryItem->getUrlPath(), '/') ?>">
                                                <li></li>
                                            </ul>
                                        </div>

                                        <div class="topnav-poplayer-main">
                                            <ul class="topnav-main-product-list">
                                                <?php foreach ($categoryItem->getChildrenCategories() as $subCategory): ?>
                                                    <li class="topnav-main-product-li">
                                                        <div class="topnav-main-title"><a
                                                                    href="<?php echo $subCategory->getUrl() ?>"><?= Mage::helper("Ave40_Translate")->__($subCategory->getName())?></a>
                                                        </div>
                                                        <ul class="topnav-main-sub-products">
                                                            <?php foreach ($subCategory->getChildrenCategories() as $threeCategory): ?>
                                                                <li>
                                                                    <a href="<?php echo $threeCategory->getUrl() ?>">
                                                                        <?php echo $this->escapeHtml(Mage::helper("Ave40_Translate")->__($threeCategory->getName())) ?>
                                                                    </a>
                                                                </li>
                                                            <?php endforeach; ?>
                                                        </ul>
                                                    </li>
                                                <?php endforeach; ?>
                                            </ul>
                                        </div>
                                    </div>
                                </li>
                            <?php endforeach; ?>

                            <?php echo Mage::app()->getLayout()->createBlock('cms/block')->setBlockId('new-navigation')->toHtml() ?>
                        </ul>
                    </div>
                </div>
				<?php avepcache_end();endif; ?>
            </div>
        </div>

        <?php
        $routeName = Mage::app()->getRequest()->getRouteName();
        $identifier = Mage::getSingleton('cms/page')->getIdentifier();
        ?>
        <?php /*if ($this->getIsHomePage() || ($routeName == 'cms' && $identifier == 'home') ):*/ ?><!--
			<div class="show-menu-content">
				<div class="show_menu"><?php /*echo $this->getChildHtml('topMenu') */ ?></div>
			</div>
		<?php /*else: */ ?>
			<div class="show-menu-content">
				<div class="hidden_menu"><?php /*echo $this->getChildHtml('topMenu') */ ?></div>
			</div>
		--><?php /*endif; */ ?>
    </div>
</div>
<div id="header-placeholder-elm" style="width:0; height:0; magin:0;"></div>

<!-- ======= popup ads begin ======= -->

<!-- 18岁提示弹窗 -->
<?php if (!$_COOKIE['18_jin_tip'] && !Mage::getStoreConfig('ave40_developer/show18notice/disabled')): ?>
    <?php //if (true): ?>

    <!-- mobile -->
    <style>
        @media (max-width: 767px) {
            .ave-18notice {
                background: url('<?= $this->getSkinUrl("images/mobile/mb_18notice.jpg") ?>') no-repeat center / 100% !important;
                width: calc(100%);
                height: 4.15rem;
            }

            .ave-18notice-body {
                height: 4.15rem;
            }

            .ave18notice-btn {
                position: absolute;
                width: 2.7rem;
                height: 0.45rem;
            }

            .ave-18notice-flase {
                bottom: 9%;
                right: 5.5%;
            }

            .ave-18notice-true {
                top: 34%;
                right: 5.5%;
            }

        }
    </style>
    <div class="ave-18notice" style="background: url('<?= $this->getSkinUrl("images/homepage/18notice-new.png") ?>')">
        <?php ob_start();
        ob_flush(); ?>
        <div class="ani-body">
            <!--<div class="ave40notice-tip">
				<img src="<? /*= $this->getSkinUrl('images/homepage/ave18-tip.png') */ ?>" alt="">
				<p><?php /*echo $this->__('The products on this website are intended for ADULTS only.') */ ?></p>
				<p><?php /*echo $this->__('Please leave this page!') */ ?></p>
				<span class="ave40-tip-close"><?php /*echo $this->__('CLOSE') */ ?></span>
			</div>-->


            <div class="ave-18notice-body">
                <span class="ave18notice-btn ave-18notice-true"><?php echo Mage::helper("Ave40_Translate")->__('Yes') ?></span>
                <span class="ave18notice-btn ave-18notice-flase"><?php echo Mage::helper("Ave40_Translate")->__('No') ?></span>

            </div>
        </div>
        <?php $obhtml = htmlspecialchars(ob_get_contents());
        ob_end_clean();
        echo $obhtml; ?>

    </div>

<?php endif; ?>

<!-- 30s ad -->
<?php if (!$_COOKIE['full_img_poped']): ?>

    <div class="giveaway-ad-popup">
        <?php ob_start();
        ob_flush(); ?>

        <?php echo Mage::app()->getLayout()->createBlock('cms/block')->setBlockId('all-page-popup-ad')->toHtml() ?>
        <a href="javascript:;" class="giveaway-ad-popup-close"></a>

        <?php $obhtml = htmlspecialchars(ob_get_contents());
        ob_end_clean();
        echo $obhtml; ?>
    </div>

    <script>
        ~function ($) {
            $(function () {
                var $giveawayAdPopup = $('.giveaway-ad-popup');
                $giveawayAdPopup.html(ave40.unescapeHtml($giveawayAdPopup.html()));

                if (ave40.getCookie('18_jin_tip')) {
                    Ave40_ads.beginCountDownFullImg();
                }

                $('.giveaway-ad-popup-close').click(function () {
                    ave40.setCookie('full_img_poped', 1, ave40.params.time.DAY * 30);
                    Ave40_ads.hideCountDownFullImg();
                })
            });

        }(jQuery);
    </script>
<?php endif; ?>

<!-- ======= popup ads end ======= -->



<?php echo Mage::app()->getLayout()->createBlock('core/template')->setTemplate('inquire/form.phtml')->toHtml() ?>

