
<!--<?=$this->getLayout()->createBlock('cms/block')->setBlockId('footer-related')->toHtml()?>-->

<div id="copyright" class="copyright clearfix">

        <div class="copyright-right certification">
            <span title="Norton" class="norton-icon"></span>
        </div>
        <div class="payment_transport">
            <span title="MasterCard"></span>
            <span title="VISA"></span>
            <span title="westernunion"></span>
            <span title="Banktransfer"></span>
            <span title="qiwi"></span>
            <span title="webmoney"></span>
            <span title="paypal"></span>
            <span title="T/T"></span>
        </div>
    <div class="copyright-text"><span><?=Mage::getStoreConfig('design/footer/copyright')?></span></div>

    <div class="mb-home-about-us">
        <a href="/about-us.html">About us</a>
        <a href="/contact-us.html">Contact us</a>
    </div>

</div>
