
<div class="best-seller-coupon christmas-clearance-p-list clearfix">
    <ul>
        <li class="coupon-item animation-itself-hover-to-up">
            <a href="/brands/vaporesso" title="SMOK" target="_blank">
                <div class="coupon-title">
                    <img src="/media/wysiwyg/topic/christmas-sales/smok.png" alt="">
                </div>

                <?php if(Mage::getSingleton('customer/session')->getCustomer()->getGroupId() != 2): ?>
                <div class="retailer-coupon christmas-coupon-code">
                    <p>15% OFF CODE</p>
                    <p>SM15OFF</p>
                </div>
                <?php else: ?>
                <div class="wholesaler-coupon christmas-coupon-code" >
                    <p>4% OFF CODE: </p>
                    <p>SMO3OFF</p>
                </div>
                <?php endif; ?>
            </a>
        </li>

        <li class="coupon-item animation-itself-hover-to-up">
            <a href="/brands/smoktech" title="vaporesso" target="_blank">
                <div class="coupon-title">
                    <img src="/media/wysiwyg/topic/christmas-sales/vaporesso.png" alt="">
                </div>

                <?php if(Mage::getSingleton('customer/session')->getCustomer()->getGroupId() != 2): ?>
                <div class="retailer-coupon christmas-coupon-code">
                    <p>15% OFF CODE</p>
                    <p>VAPO15OFF</p>
                </div>
                <?php else: ?>
                <div class="wholesaler-coupon christmas-coupon-code" >
                    <p>5% OFF CODE: </p>
                    <p>VAP25OFF</p>
                </div>
                <?php endif; ?>
            </a>
        </li>
        <li class="coupon-item animation-itself-hover-to-up">
            <a href="starter-kits/close-system" title="CLOSE SYSTEM" target="_blank">
                <div class="coupon-title">
                    <span>CLOSE SYSTEM</span>
                </div>
                <?php if(Mage::getSingleton('customer/session')->getCustomer()->getGroupId() != 2): ?>
                <div class="retailer-coupon christmas-coupon-code">
                    <p>25% OFF CODE</p>
                    <p>CLOSES25</p>
                </div>
                <?php else: ?>
                <div class="wholesaler-coupon christmas-coupon-code" >
                    <p>3% OFF CODE: </p>
                    <p>CLOSE3OFF</p>
                </div>
                <?php endif; ?>
            </a>
        </li>
        <li class="coupon-item animation-itself-hover-to-up">
            <a href="/starter-kits" title="starter kits" target="_blank">
                <div class="coupon-title">
                    <span>STARTER KIT</span>
                </div>
                <?php if(Mage::getSingleton('customer/session')->getCustomer()->getGroupId() != 2): ?>
                <div class="retailer-coupon christmas-coupon-code">
                    <p>15% OFF CODE</p>
                    <p>STARTER15</p>
                </div>
                <?php else: ?>
                <div class="wholesaler-coupon christmas-coupon-code" >
                    <p>4% OFF CODE: </p>
                    <p>STARTER04</p>
                </div>
                <?php endif; ?>
            </a>
        </li>
    </ul>
</div>
