<?php $_model = Mage::getModel('braintree_payments/paymentmethod'); ?>
<?php if ($_model): ?>
<script type="text/javascript">
    if (typeof Review !== 'undefined') {
        var _super;

        if (typeof _super === 'undefined' && typeof _super !== 'function')
            _super = Review.prototype.save;

        Review.prototype.save = function() {
            if (payment.currentMethod !== 'braintree') {
                return _super.apply(this);
            }

            braintree = Braintree.create('<?php echo $_model->getConfigData('client_side_encryption_key') ?>');
            braintree.encryptForm(payment.form);

            if (checkout.loadWaiting!=false) return;
            checkout.setLoadWaiting('review');

            params = $(payment.form).serialize();

            if (this.agreementsForm) {
                params += '&'+Form.serialize(this.agreementsForm);
            }
            params.save = true;
            var request = new Ajax.Request(
                this.saveUrl,
                {
                    method:'post',
                    parameters:params,
                    onComplete: this.onComplete,
                    onSuccess: this.onSave,
                    onFailure: checkout.ajaxFailure.bind(checkout)
                }
            );
        };
    }
    if ($('onestepcheckout-place-order')) {
        Event.observe('onestepcheckout-place-order', 'click', function(e){
            if (payment.currentMethod === 'braintree') {
                braintree = Braintree.create('<?php echo $_model->getConfigData('client_side_encryption_key') ?>');
                braintree.encryptForm(payment.form);
            }
        });
    }
</script>
<?php endif; ?>
