<?php if ($this->isPossibleOnepageCheckout()):?>
    <button type="button" title="<?php echo Mage::helper("Ave40_Translate")->__('Proceed to Checkout') ?>" class="button btn-round btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';"><span><span><?php echo Mage::helper("Ave40_Translate")->__('Proceed to Checkout') ?></span></span></button>
<?php endif?>
